/*
 * Ed-Fi Operational Data Store API
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Models.Resources;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * EdFiEducationOrganizationInternationalAddress
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-28T14:58:32.034-05:00[America/Mexico_City]")
public class EdFiEducationOrganizationInternationalAddress {
  public static final String SERIALIZED_NAME_ADDRESS_TYPE_DESCRIPTOR = "addressTypeDescriptor";
  @SerializedName(SERIALIZED_NAME_ADDRESS_TYPE_DESCRIPTOR)
  private String addressTypeDescriptor;

  public static final String SERIALIZED_NAME_COUNTRY_DESCRIPTOR = "countryDescriptor";
  @SerializedName(SERIALIZED_NAME_COUNTRY_DESCRIPTOR)
  private String countryDescriptor;

  public static final String SERIALIZED_NAME_ADDRESS_LINE1 = "addressLine1";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE1)
  private String addressLine1;

  public static final String SERIALIZED_NAME_ADDRESS_LINE2 = "addressLine2";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE2)
  private String addressLine2;

  public static final String SERIALIZED_NAME_ADDRESS_LINE3 = "addressLine3";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE3)
  private String addressLine3;

  public static final String SERIALIZED_NAME_ADDRESS_LINE4 = "addressLine4";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE4)
  private String addressLine4;

  public static final String SERIALIZED_NAME_BEGIN_DATE = "beginDate";
  @SerializedName(SERIALIZED_NAME_BEGIN_DATE)
  private LocalDate beginDate;

  public static final String SERIALIZED_NAME_END_DATE = "endDate";
  @SerializedName(SERIALIZED_NAME_END_DATE)
  private LocalDate endDate;

  public static final String SERIALIZED_NAME_LATITUDE = "latitude";
  @SerializedName(SERIALIZED_NAME_LATITUDE)
  private String latitude;

  public static final String SERIALIZED_NAME_LONGITUDE = "longitude";
  @SerializedName(SERIALIZED_NAME_LONGITUDE)
  private String longitude;

  public EdFiEducationOrganizationInternationalAddress() { 
  }

  public EdFiEducationOrganizationInternationalAddress addressTypeDescriptor(String addressTypeDescriptor) {
    
    this.addressTypeDescriptor = addressTypeDescriptor;
    return this;
  }

   /**
   * The type of address listed for an individual or organization. For example:  Physical Address, Mailing Address, Home Address, etc.)
   * @return addressTypeDescriptor
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The type of address listed for an individual or organization. For example:  Physical Address, Mailing Address, Home Address, etc.)")

  public String getAddressTypeDescriptor() {
    return addressTypeDescriptor;
  }


  public void setAddressTypeDescriptor(String addressTypeDescriptor) {
    this.addressTypeDescriptor = addressTypeDescriptor;
  }


  public EdFiEducationOrganizationInternationalAddress countryDescriptor(String countryDescriptor) {
    
    this.countryDescriptor = countryDescriptor;
    return this;
  }

   /**
   * The name of the country. It is strongly recommended that entries use only ISO 3166 2-letter country codes.
   * @return countryDescriptor
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The name of the country. It is strongly recommended that entries use only ISO 3166 2-letter country codes.")

  public String getCountryDescriptor() {
    return countryDescriptor;
  }


  public void setCountryDescriptor(String countryDescriptor) {
    this.countryDescriptor = countryDescriptor;
  }


  public EdFiEducationOrganizationInternationalAddress addressLine1(String addressLine1) {
    
    this.addressLine1 = addressLine1;
    return this;
  }

   /**
   * The first line of the address.
   * @return addressLine1
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The first line of the address.")

  public String getAddressLine1() {
    return addressLine1;
  }


  public void setAddressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
  }


  public EdFiEducationOrganizationInternationalAddress addressLine2(String addressLine2) {
    
    this.addressLine2 = addressLine2;
    return this;
  }

   /**
   * The second line of the address.
   * @return addressLine2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The second line of the address.")

  public String getAddressLine2() {
    return addressLine2;
  }


  public void setAddressLine2(String addressLine2) {
    this.addressLine2 = addressLine2;
  }


  public EdFiEducationOrganizationInternationalAddress addressLine3(String addressLine3) {
    
    this.addressLine3 = addressLine3;
    return this;
  }

   /**
   * The third line of the address.
   * @return addressLine3
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The third line of the address.")

  public String getAddressLine3() {
    return addressLine3;
  }


  public void setAddressLine3(String addressLine3) {
    this.addressLine3 = addressLine3;
  }


  public EdFiEducationOrganizationInternationalAddress addressLine4(String addressLine4) {
    
    this.addressLine4 = addressLine4;
    return this;
  }

   /**
   * The fourth line of the address.
   * @return addressLine4
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The fourth line of the address.")

  public String getAddressLine4() {
    return addressLine4;
  }


  public void setAddressLine4(String addressLine4) {
    this.addressLine4 = addressLine4;
  }


  public EdFiEducationOrganizationInternationalAddress beginDate(LocalDate beginDate) {
    
    this.beginDate = beginDate;
    return this;
  }

   /**
   * The first date the address is valid. For physical addresses, the date the person moved to that address.
   * @return beginDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The first date the address is valid. For physical addresses, the date the person moved to that address.")

  public LocalDate getBeginDate() {
    return beginDate;
  }


  public void setBeginDate(LocalDate beginDate) {
    this.beginDate = beginDate;
  }


  public EdFiEducationOrganizationInternationalAddress endDate(LocalDate endDate) {
    
    this.endDate = endDate;
    return this;
  }

   /**
   * The last date the address is valid. For physical addresses, this would be the date the person moved from that address.
   * @return endDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The last date the address is valid. For physical addresses, this would be the date the person moved from that address.")

  public LocalDate getEndDate() {
    return endDate;
  }


  public void setEndDate(LocalDate endDate) {
    this.endDate = endDate;
  }


  public EdFiEducationOrganizationInternationalAddress latitude(String latitude) {
    
    this.latitude = latitude;
    return this;
  }

   /**
   * The geographic latitude of the physical address.
   * @return latitude
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The geographic latitude of the physical address.")

  public String getLatitude() {
    return latitude;
  }


  public void setLatitude(String latitude) {
    this.latitude = latitude;
  }


  public EdFiEducationOrganizationInternationalAddress longitude(String longitude) {
    
    this.longitude = longitude;
    return this;
  }

   /**
   * The geographic longitude of the physical address.
   * @return longitude
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The geographic longitude of the physical address.")

  public String getLongitude() {
    return longitude;
  }


  public void setLongitude(String longitude) {
    this.longitude = longitude;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EdFiEducationOrganizationInternationalAddress edFiEducationOrganizationInternationalAddress = (EdFiEducationOrganizationInternationalAddress) o;
    return Objects.equals(this.addressTypeDescriptor, edFiEducationOrganizationInternationalAddress.addressTypeDescriptor) &&
        Objects.equals(this.countryDescriptor, edFiEducationOrganizationInternationalAddress.countryDescriptor) &&
        Objects.equals(this.addressLine1, edFiEducationOrganizationInternationalAddress.addressLine1) &&
        Objects.equals(this.addressLine2, edFiEducationOrganizationInternationalAddress.addressLine2) &&
        Objects.equals(this.addressLine3, edFiEducationOrganizationInternationalAddress.addressLine3) &&
        Objects.equals(this.addressLine4, edFiEducationOrganizationInternationalAddress.addressLine4) &&
        Objects.equals(this.beginDate, edFiEducationOrganizationInternationalAddress.beginDate) &&
        Objects.equals(this.endDate, edFiEducationOrganizationInternationalAddress.endDate) &&
        Objects.equals(this.latitude, edFiEducationOrganizationInternationalAddress.latitude) &&
        Objects.equals(this.longitude, edFiEducationOrganizationInternationalAddress.longitude);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressTypeDescriptor, countryDescriptor, addressLine1, addressLine2, addressLine3, addressLine4, beginDate, endDate, latitude, longitude);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EdFiEducationOrganizationInternationalAddress {\n");
    sb.append("    addressTypeDescriptor: ").append(toIndentedString(addressTypeDescriptor)).append("\n");
    sb.append("    countryDescriptor: ").append(toIndentedString(countryDescriptor)).append("\n");
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    addressLine2: ").append(toIndentedString(addressLine2)).append("\n");
    sb.append("    addressLine3: ").append(toIndentedString(addressLine3)).append("\n");
    sb.append("    addressLine4: ").append(toIndentedString(addressLine4)).append("\n");
    sb.append("    beginDate: ").append(toIndentedString(beginDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

