/*
 * Ed-Fi Operational Data Store API
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Models.Resources;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * EdFiStudentEducationOrganizationAssociationLanguageUse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-28T14:58:32.034-05:00[America/Mexico_City]")
public class EdFiStudentEducationOrganizationAssociationLanguageUse {
  public static final String SERIALIZED_NAME_LANGUAGE_USE_DESCRIPTOR = "languageUseDescriptor";
  @SerializedName(SERIALIZED_NAME_LANGUAGE_USE_DESCRIPTOR)
  private String languageUseDescriptor;

  public EdFiStudentEducationOrganizationAssociationLanguageUse() { 
  }

  public EdFiStudentEducationOrganizationAssociationLanguageUse languageUseDescriptor(String languageUseDescriptor) {
    
    this.languageUseDescriptor = languageUseDescriptor;
    return this;
  }

   /**
   * A description of how the language is used (e.g. Home Language, Native Language, Spoken Language).
   * @return languageUseDescriptor
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A description of how the language is used (e.g. Home Language, Native Language, Spoken Language).")

  public String getLanguageUseDescriptor() {
    return languageUseDescriptor;
  }


  public void setLanguageUseDescriptor(String languageUseDescriptor) {
    this.languageUseDescriptor = languageUseDescriptor;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EdFiStudentEducationOrganizationAssociationLanguageUse edFiStudentEducationOrganizationAssociationLanguageUse = (EdFiStudentEducationOrganizationAssociationLanguageUse) o;
    return Objects.equals(this.languageUseDescriptor, edFiStudentEducationOrganizationAssociationLanguageUse.languageUseDescriptor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(languageUseDescriptor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EdFiStudentEducationOrganizationAssociationLanguageUse {\n");
    sb.append("    languageUseDescriptor: ").append(toIndentedString(languageUseDescriptor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

