/*
 * Ed-Fi Operational Data Store API
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Models.Resources;

import java.util.Objects;
import java.util.Arrays;
import Models.Resources.EdFiEducationOrganizationReference;
import Models.Resources.EdFiStudentEducationOrganizationAssociationAddress;
import Models.Resources.EdFiStudentEducationOrganizationAssociationAncestryEthnicOrigin;
import Models.Resources.EdFiStudentEducationOrganizationAssociationCohortYear;
import Models.Resources.EdFiStudentEducationOrganizationAssociationDisability;
import Models.Resources.EdFiStudentEducationOrganizationAssociationElectronicMail;
import Models.Resources.EdFiStudentEducationOrganizationAssociationInternationalAddress;
import Models.Resources.EdFiStudentEducationOrganizationAssociationLanguage;
import Models.Resources.EdFiStudentEducationOrganizationAssociationProgramParticipation;
import Models.Resources.EdFiStudentEducationOrganizationAssociationRace;
import Models.Resources.EdFiStudentEducationOrganizationAssociationStudentCharacteristic;
import Models.Resources.EdFiStudentEducationOrganizationAssociationStudentIdentificationCode;
import Models.Resources.EdFiStudentEducationOrganizationAssociationStudentIndicator;
import Models.Resources.EdFiStudentEducationOrganizationAssociationTelephone;
import Models.Resources.EdFiStudentEducationOrganizationAssociationTribalAffiliation;
import Models.Resources.EdFiStudentReference;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * EdFiStudentEducationOrganizationAssociation
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-28T14:58:32.034-05:00[America/Mexico_City]")
public class EdFiStudentEducationOrganizationAssociation {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_EDUCATION_ORGANIZATION_REFERENCE = "educationOrganizationReference";
  @SerializedName(SERIALIZED_NAME_EDUCATION_ORGANIZATION_REFERENCE)
  private EdFiEducationOrganizationReference educationOrganizationReference;

  public static final String SERIALIZED_NAME_STUDENT_REFERENCE = "studentReference";
  @SerializedName(SERIALIZED_NAME_STUDENT_REFERENCE)
  private EdFiStudentReference studentReference;

  public static final String SERIALIZED_NAME_ADDRESSES = "addresses";
  @SerializedName(SERIALIZED_NAME_ADDRESSES)
  private List<EdFiStudentEducationOrganizationAssociationAddress> addresses = null;

  public static final String SERIALIZED_NAME_ANCESTRY_ETHNIC_ORIGINS = "ancestryEthnicOrigins";
  @SerializedName(SERIALIZED_NAME_ANCESTRY_ETHNIC_ORIGINS)
  private List<EdFiStudentEducationOrganizationAssociationAncestryEthnicOrigin> ancestryEthnicOrigins = null;

  public static final String SERIALIZED_NAME_COHORT_YEARS = "cohortYears";
  @SerializedName(SERIALIZED_NAME_COHORT_YEARS)
  private List<EdFiStudentEducationOrganizationAssociationCohortYear> cohortYears = null;

  public static final String SERIALIZED_NAME_DISABILITIES = "disabilities";
  @SerializedName(SERIALIZED_NAME_DISABILITIES)
  private List<EdFiStudentEducationOrganizationAssociationDisability> disabilities = null;

  public static final String SERIALIZED_NAME_ELECTRONIC_MAILS = "electronicMails";
  @SerializedName(SERIALIZED_NAME_ELECTRONIC_MAILS)
  private List<EdFiStudentEducationOrganizationAssociationElectronicMail> electronicMails = null;

  public static final String SERIALIZED_NAME_HISPANIC_LATINO_ETHNICITY = "hispanicLatinoEthnicity";
  @SerializedName(SERIALIZED_NAME_HISPANIC_LATINO_ETHNICITY)
  private Boolean hispanicLatinoEthnicity;

  public static final String SERIALIZED_NAME_INTERNATIONAL_ADDRESSES = "internationalAddresses";
  @SerializedName(SERIALIZED_NAME_INTERNATIONAL_ADDRESSES)
  private List<EdFiStudentEducationOrganizationAssociationInternationalAddress> internationalAddresses = null;

  public static final String SERIALIZED_NAME_LANGUAGES = "languages";
  @SerializedName(SERIALIZED_NAME_LANGUAGES)
  private List<EdFiStudentEducationOrganizationAssociationLanguage> languages = null;

  public static final String SERIALIZED_NAME_LIMITED_ENGLISH_PROFICIENCY_DESCRIPTOR = "limitedEnglishProficiencyDescriptor";
  @SerializedName(SERIALIZED_NAME_LIMITED_ENGLISH_PROFICIENCY_DESCRIPTOR)
  private String limitedEnglishProficiencyDescriptor;

  public static final String SERIALIZED_NAME_LOGIN_ID = "loginId";
  @SerializedName(SERIALIZED_NAME_LOGIN_ID)
  private String loginId;

  public static final String SERIALIZED_NAME_OLD_ETHNICITY_DESCRIPTOR = "oldEthnicityDescriptor";
  @SerializedName(SERIALIZED_NAME_OLD_ETHNICITY_DESCRIPTOR)
  private String oldEthnicityDescriptor;

  public static final String SERIALIZED_NAME_PROFILE_THUMBNAIL = "profileThumbnail";
  @SerializedName(SERIALIZED_NAME_PROFILE_THUMBNAIL)
  private String profileThumbnail;

  public static final String SERIALIZED_NAME_PROGRAM_PARTICIPATIONS = "programParticipations";
  @SerializedName(SERIALIZED_NAME_PROGRAM_PARTICIPATIONS)
  private List<EdFiStudentEducationOrganizationAssociationProgramParticipation> programParticipations = null;

  public static final String SERIALIZED_NAME_RACES = "races";
  @SerializedName(SERIALIZED_NAME_RACES)
  private List<EdFiStudentEducationOrganizationAssociationRace> races = null;

  public static final String SERIALIZED_NAME_SEX_DESCRIPTOR = "sexDescriptor";
  @SerializedName(SERIALIZED_NAME_SEX_DESCRIPTOR)
  private String sexDescriptor;

  public static final String SERIALIZED_NAME_STUDENT_CHARACTERISTICS = "studentCharacteristics";
  @SerializedName(SERIALIZED_NAME_STUDENT_CHARACTERISTICS)
  private List<EdFiStudentEducationOrganizationAssociationStudentCharacteristic> studentCharacteristics = null;

  public static final String SERIALIZED_NAME_STUDENT_IDENTIFICATION_CODES = "studentIdentificationCodes";
  @SerializedName(SERIALIZED_NAME_STUDENT_IDENTIFICATION_CODES)
  private List<EdFiStudentEducationOrganizationAssociationStudentIdentificationCode> studentIdentificationCodes = null;

  public static final String SERIALIZED_NAME_STUDENT_INDICATORS = "studentIndicators";
  @SerializedName(SERIALIZED_NAME_STUDENT_INDICATORS)
  private List<EdFiStudentEducationOrganizationAssociationStudentIndicator> studentIndicators = null;

  public static final String SERIALIZED_NAME_TELEPHONES = "telephones";
  @SerializedName(SERIALIZED_NAME_TELEPHONES)
  private List<EdFiStudentEducationOrganizationAssociationTelephone> telephones = null;

  public static final String SERIALIZED_NAME_TRIBAL_AFFILIATIONS = "tribalAffiliations";
  @SerializedName(SERIALIZED_NAME_TRIBAL_AFFILIATIONS)
  private List<EdFiStudentEducationOrganizationAssociationTribalAffiliation> tribalAffiliations = null;

  public static final String SERIALIZED_NAME_ETAG = "_etag";
  @SerializedName(SERIALIZED_NAME_ETAG)
  private String etag;

  public EdFiStudentEducationOrganizationAssociation() { 
  }

  public EdFiStudentEducationOrganizationAssociation id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public EdFiStudentEducationOrganizationAssociation educationOrganizationReference(EdFiEducationOrganizationReference educationOrganizationReference) {
    
    this.educationOrganizationReference = educationOrganizationReference;
    return this;
  }

   /**
   * Get educationOrganizationReference
   * @return educationOrganizationReference
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public EdFiEducationOrganizationReference getEducationOrganizationReference() {
    return educationOrganizationReference;
  }


  public void setEducationOrganizationReference(EdFiEducationOrganizationReference educationOrganizationReference) {
    this.educationOrganizationReference = educationOrganizationReference;
  }


  public EdFiStudentEducationOrganizationAssociation studentReference(EdFiStudentReference studentReference) {
    
    this.studentReference = studentReference;
    return this;
  }

   /**
   * Get studentReference
   * @return studentReference
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public EdFiStudentReference getStudentReference() {
    return studentReference;
  }


  public void setStudentReference(EdFiStudentReference studentReference) {
    this.studentReference = studentReference;
  }


  public EdFiStudentEducationOrganizationAssociation addresses(List<EdFiStudentEducationOrganizationAssociationAddress> addresses) {
    
    this.addresses = addresses;
    return this;
  }

  public EdFiStudentEducationOrganizationAssociation addAddressesItem(EdFiStudentEducationOrganizationAssociationAddress addressesItem) {
    if (this.addresses == null) {
      this.addresses = new ArrayList<EdFiStudentEducationOrganizationAssociationAddress>();
    }
    this.addresses.add(addressesItem);
    return this;
  }

   /**
   * An unordered collection of studentEducationOrganizationAssociationAddresses. The set of elements that describes an address, including the street address, city, state, and ZIP code.
   * @return addresses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An unordered collection of studentEducationOrganizationAssociationAddresses. The set of elements that describes an address, including the street address, city, state, and ZIP code.")

  public List<EdFiStudentEducationOrganizationAssociationAddress> getAddresses() {
    return addresses;
  }


  public void setAddresses(List<EdFiStudentEducationOrganizationAssociationAddress> addresses) {
    this.addresses = addresses;
  }


  public EdFiStudentEducationOrganizationAssociation ancestryEthnicOrigins(List<EdFiStudentEducationOrganizationAssociationAncestryEthnicOrigin> ancestryEthnicOrigins) {
    
    this.ancestryEthnicOrigins = ancestryEthnicOrigins;
    return this;
  }

  public EdFiStudentEducationOrganizationAssociation addAncestryEthnicOriginsItem(EdFiStudentEducationOrganizationAssociationAncestryEthnicOrigin ancestryEthnicOriginsItem) {
    if (this.ancestryEthnicOrigins == null) {
      this.ancestryEthnicOrigins = new ArrayList<EdFiStudentEducationOrganizationAssociationAncestryEthnicOrigin>();
    }
    this.ancestryEthnicOrigins.add(ancestryEthnicOriginsItem);
    return this;
  }

   /**
   * An unordered collection of studentEducationOrganizationAssociationAncestryEthnicOrigins. The original peoples or cultures with which the individual identifies.
   * @return ancestryEthnicOrigins
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An unordered collection of studentEducationOrganizationAssociationAncestryEthnicOrigins. The original peoples or cultures with which the individual identifies.")

  public List<EdFiStudentEducationOrganizationAssociationAncestryEthnicOrigin> getAncestryEthnicOrigins() {
    return ancestryEthnicOrigins;
  }


  public void setAncestryEthnicOrigins(List<EdFiStudentEducationOrganizationAssociationAncestryEthnicOrigin> ancestryEthnicOrigins) {
    this.ancestryEthnicOrigins = ancestryEthnicOrigins;
  }


  public EdFiStudentEducationOrganizationAssociation cohortYears(List<EdFiStudentEducationOrganizationAssociationCohortYear> cohortYears) {
    
    this.cohortYears = cohortYears;
    return this;
  }

  public EdFiStudentEducationOrganizationAssociation addCohortYearsItem(EdFiStudentEducationOrganizationAssociationCohortYear cohortYearsItem) {
    if (this.cohortYears == null) {
      this.cohortYears = new ArrayList<EdFiStudentEducationOrganizationAssociationCohortYear>();
    }
    this.cohortYears.add(cohortYearsItem);
    return this;
  }

   /**
   * An unordered collection of studentEducationOrganizationAssociationCohortYears. The type and year of a cohort (e.g., 9th grade) the student belongs to as determined by the year that student entered a specific grade.
   * @return cohortYears
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An unordered collection of studentEducationOrganizationAssociationCohortYears. The type and year of a cohort (e.g., 9th grade) the student belongs to as determined by the year that student entered a specific grade.")

  public List<EdFiStudentEducationOrganizationAssociationCohortYear> getCohortYears() {
    return cohortYears;
  }


  public void setCohortYears(List<EdFiStudentEducationOrganizationAssociationCohortYear> cohortYears) {
    this.cohortYears = cohortYears;
  }


  public EdFiStudentEducationOrganizationAssociation disabilities(List<EdFiStudentEducationOrganizationAssociationDisability> disabilities) {
    
    this.disabilities = disabilities;
    return this;
  }

  public EdFiStudentEducationOrganizationAssociation addDisabilitiesItem(EdFiStudentEducationOrganizationAssociationDisability disabilitiesItem) {
    if (this.disabilities == null) {
      this.disabilities = new ArrayList<EdFiStudentEducationOrganizationAssociationDisability>();
    }
    this.disabilities.add(disabilitiesItem);
    return this;
  }

   /**
   * An unordered collection of studentEducationOrganizationAssociationDisabilities. The disability condition(s) that best describes an individual&#39;s impairment, as determined by evaluation(s) conducted by the education organization.
   * @return disabilities
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An unordered collection of studentEducationOrganizationAssociationDisabilities. The disability condition(s) that best describes an individual's impairment, as determined by evaluation(s) conducted by the education organization.")

  public List<EdFiStudentEducationOrganizationAssociationDisability> getDisabilities() {
    return disabilities;
  }


  public void setDisabilities(List<EdFiStudentEducationOrganizationAssociationDisability> disabilities) {
    this.disabilities = disabilities;
  }


  public EdFiStudentEducationOrganizationAssociation electronicMails(List<EdFiStudentEducationOrganizationAssociationElectronicMail> electronicMails) {
    
    this.electronicMails = electronicMails;
    return this;
  }

  public EdFiStudentEducationOrganizationAssociation addElectronicMailsItem(EdFiStudentEducationOrganizationAssociationElectronicMail electronicMailsItem) {
    if (this.electronicMails == null) {
      this.electronicMails = new ArrayList<EdFiStudentEducationOrganizationAssociationElectronicMail>();
    }
    this.electronicMails.add(electronicMailsItem);
    return this;
  }

   /**
   * An unordered collection of studentEducationOrganizationAssociationElectronicMails. The numbers, letters, and symbols used to identify an electronic mail (e-mail) user within the network to which the individual or organization belongs.
   * @return electronicMails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An unordered collection of studentEducationOrganizationAssociationElectronicMails. The numbers, letters, and symbols used to identify an electronic mail (e-mail) user within the network to which the individual or organization belongs.")

  public List<EdFiStudentEducationOrganizationAssociationElectronicMail> getElectronicMails() {
    return electronicMails;
  }


  public void setElectronicMails(List<EdFiStudentEducationOrganizationAssociationElectronicMail> electronicMails) {
    this.electronicMails = electronicMails;
  }


  public EdFiStudentEducationOrganizationAssociation hispanicLatinoEthnicity(Boolean hispanicLatinoEthnicity) {
    
    this.hispanicLatinoEthnicity = hispanicLatinoEthnicity;
    return this;
  }

   /**
   * An indication that the individual traces his or her origin or descent to Mexico, Puerto Rico, Cuba, Central, and South America, and other Spanish cultures, regardless of race, as last reported to the education organization. The term, \&quot;Spanish origin,\&quot; can be used in addition to \&quot;Hispanic or Latino.\&quot;
   * @return hispanicLatinoEthnicity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An indication that the individual traces his or her origin or descent to Mexico, Puerto Rico, Cuba, Central, and South America, and other Spanish cultures, regardless of race, as last reported to the education organization. The term, \"Spanish origin,\" can be used in addition to \"Hispanic or Latino.\"")

  public Boolean getHispanicLatinoEthnicity() {
    return hispanicLatinoEthnicity;
  }


  public void setHispanicLatinoEthnicity(Boolean hispanicLatinoEthnicity) {
    this.hispanicLatinoEthnicity = hispanicLatinoEthnicity;
  }


  public EdFiStudentEducationOrganizationAssociation internationalAddresses(List<EdFiStudentEducationOrganizationAssociationInternationalAddress> internationalAddresses) {
    
    this.internationalAddresses = internationalAddresses;
    return this;
  }

  public EdFiStudentEducationOrganizationAssociation addInternationalAddressesItem(EdFiStudentEducationOrganizationAssociationInternationalAddress internationalAddressesItem) {
    if (this.internationalAddresses == null) {
      this.internationalAddresses = new ArrayList<EdFiStudentEducationOrganizationAssociationInternationalAddress>();
    }
    this.internationalAddresses.add(internationalAddressesItem);
    return this;
  }

   /**
   * An unordered collection of studentEducationOrganizationAssociationInternationalAddresses. The set of elements that describes an international address.
   * @return internationalAddresses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An unordered collection of studentEducationOrganizationAssociationInternationalAddresses. The set of elements that describes an international address.")

  public List<EdFiStudentEducationOrganizationAssociationInternationalAddress> getInternationalAddresses() {
    return internationalAddresses;
  }


  public void setInternationalAddresses(List<EdFiStudentEducationOrganizationAssociationInternationalAddress> internationalAddresses) {
    this.internationalAddresses = internationalAddresses;
  }


  public EdFiStudentEducationOrganizationAssociation languages(List<EdFiStudentEducationOrganizationAssociationLanguage> languages) {
    
    this.languages = languages;
    return this;
  }

  public EdFiStudentEducationOrganizationAssociation addLanguagesItem(EdFiStudentEducationOrganizationAssociationLanguage languagesItem) {
    if (this.languages == null) {
      this.languages = new ArrayList<EdFiStudentEducationOrganizationAssociationLanguage>();
    }
    this.languages.add(languagesItem);
    return this;
  }

   /**
   * An unordered collection of studentEducationOrganizationAssociationLanguages. The language(s) the individual uses to communicate. It is strongly recommended that entries use only ISO 639-3 language codes.
   * @return languages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An unordered collection of studentEducationOrganizationAssociationLanguages. The language(s) the individual uses to communicate. It is strongly recommended that entries use only ISO 639-3 language codes.")

  public List<EdFiStudentEducationOrganizationAssociationLanguage> getLanguages() {
    return languages;
  }


  public void setLanguages(List<EdFiStudentEducationOrganizationAssociationLanguage> languages) {
    this.languages = languages;
  }


  public EdFiStudentEducationOrganizationAssociation limitedEnglishProficiencyDescriptor(String limitedEnglishProficiencyDescriptor) {
    
    this.limitedEnglishProficiencyDescriptor = limitedEnglishProficiencyDescriptor;
    return this;
  }

   /**
   * An indication that the student has been identified as limited English proficient by the Language Proficiency Assessment Committee (LPAC), or English proficient.
   * @return limitedEnglishProficiencyDescriptor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An indication that the student has been identified as limited English proficient by the Language Proficiency Assessment Committee (LPAC), or English proficient.")

  public String getLimitedEnglishProficiencyDescriptor() {
    return limitedEnglishProficiencyDescriptor;
  }


  public void setLimitedEnglishProficiencyDescriptor(String limitedEnglishProficiencyDescriptor) {
    this.limitedEnglishProficiencyDescriptor = limitedEnglishProficiencyDescriptor;
  }


  public EdFiStudentEducationOrganizationAssociation loginId(String loginId) {
    
    this.loginId = loginId;
    return this;
  }

   /**
   * The login ID for the user; used for security access control interface.
   * @return loginId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The login ID for the user; used for security access control interface.")

  public String getLoginId() {
    return loginId;
  }


  public void setLoginId(String loginId) {
    this.loginId = loginId;
  }


  public EdFiStudentEducationOrganizationAssociation oldEthnicityDescriptor(String oldEthnicityDescriptor) {
    
    this.oldEthnicityDescriptor = oldEthnicityDescriptor;
    return this;
  }

   /**
   * Previous definition of Ethnicity combining Hispanic/Latino and race:         1 - American Indian or Alaskan Native         2 - Asian or Pacific Islander         3 - Black, not of Hispanic origin         4 - Hispanic         5 - White, not of Hispanic origin.
   * @return oldEthnicityDescriptor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Previous definition of Ethnicity combining Hispanic/Latino and race:         1 - American Indian or Alaskan Native         2 - Asian or Pacific Islander         3 - Black, not of Hispanic origin         4 - Hispanic         5 - White, not of Hispanic origin.")

  public String getOldEthnicityDescriptor() {
    return oldEthnicityDescriptor;
  }


  public void setOldEthnicityDescriptor(String oldEthnicityDescriptor) {
    this.oldEthnicityDescriptor = oldEthnicityDescriptor;
  }


  public EdFiStudentEducationOrganizationAssociation profileThumbnail(String profileThumbnail) {
    
    this.profileThumbnail = profileThumbnail;
    return this;
  }

   /**
   * Locator reference for the student photo. The specification for that reference is left to local definition.
   * @return profileThumbnail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Locator reference for the student photo. The specification for that reference is left to local definition.")

  public String getProfileThumbnail() {
    return profileThumbnail;
  }


  public void setProfileThumbnail(String profileThumbnail) {
    this.profileThumbnail = profileThumbnail;
  }


  public EdFiStudentEducationOrganizationAssociation programParticipations(List<EdFiStudentEducationOrganizationAssociationProgramParticipation> programParticipations) {
    
    this.programParticipations = programParticipations;
    return this;
  }

  public EdFiStudentEducationOrganizationAssociation addProgramParticipationsItem(EdFiStudentEducationOrganizationAssociationProgramParticipation programParticipationsItem) {
    if (this.programParticipations == null) {
      this.programParticipations = new ArrayList<EdFiStudentEducationOrganizationAssociationProgramParticipation>();
    }
    this.programParticipations.add(programParticipationsItem);
    return this;
  }

   /**
   * An unordered collection of studentEducationOrganizationAssociationProgramParticipations. Key programs the student is participating in or receives services from.
   * @return programParticipations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An unordered collection of studentEducationOrganizationAssociationProgramParticipations. Key programs the student is participating in or receives services from.")

  public List<EdFiStudentEducationOrganizationAssociationProgramParticipation> getProgramParticipations() {
    return programParticipations;
  }


  public void setProgramParticipations(List<EdFiStudentEducationOrganizationAssociationProgramParticipation> programParticipations) {
    this.programParticipations = programParticipations;
  }


  public EdFiStudentEducationOrganizationAssociation races(List<EdFiStudentEducationOrganizationAssociationRace> races) {
    
    this.races = races;
    return this;
  }

  public EdFiStudentEducationOrganizationAssociation addRacesItem(EdFiStudentEducationOrganizationAssociationRace racesItem) {
    if (this.races == null) {
      this.races = new ArrayList<EdFiStudentEducationOrganizationAssociationRace>();
    }
    this.races.add(racesItem);
    return this;
  }

   /**
   * An unordered collection of studentEducationOrganizationAssociationRaces. The general racial category which most clearly reflects the individual&#39;s recognition of his or her community or with which the individual most identifies as last reported to the education organization. The data model allows for multiple entries so that each individual can specify all appropriate races.
   * @return races
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An unordered collection of studentEducationOrganizationAssociationRaces. The general racial category which most clearly reflects the individual's recognition of his or her community or with which the individual most identifies as last reported to the education organization. The data model allows for multiple entries so that each individual can specify all appropriate races.")

  public List<EdFiStudentEducationOrganizationAssociationRace> getRaces() {
    return races;
  }


  public void setRaces(List<EdFiStudentEducationOrganizationAssociationRace> races) {
    this.races = races;
  }


  public EdFiStudentEducationOrganizationAssociation sexDescriptor(String sexDescriptor) {
    
    this.sexDescriptor = sexDescriptor;
    return this;
  }

   /**
   * The student&#39;s gender as last reported to the education organization.
   * @return sexDescriptor
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The student's gender as last reported to the education organization.")

  public String getSexDescriptor() {
    return sexDescriptor;
  }


  public void setSexDescriptor(String sexDescriptor) {
    this.sexDescriptor = sexDescriptor;
  }


  public EdFiStudentEducationOrganizationAssociation studentCharacteristics(List<EdFiStudentEducationOrganizationAssociationStudentCharacteristic> studentCharacteristics) {
    
    this.studentCharacteristics = studentCharacteristics;
    return this;
  }

  public EdFiStudentEducationOrganizationAssociation addStudentCharacteristicsItem(EdFiStudentEducationOrganizationAssociationStudentCharacteristic studentCharacteristicsItem) {
    if (this.studentCharacteristics == null) {
      this.studentCharacteristics = new ArrayList<EdFiStudentEducationOrganizationAssociationStudentCharacteristic>();
    }
    this.studentCharacteristics.add(studentCharacteristicsItem);
    return this;
  }

   /**
   * An unordered collection of studentEducationOrganizationAssociationStudentCharacteristics. Reflects important characteristics of a student. If a student has a characteristic present, that characteristic is considered true or active for that student. If a characteristic is not present, no assumption is made as to the applicability of the characteristic, but local policy may dictate otherwise.
   * @return studentCharacteristics
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An unordered collection of studentEducationOrganizationAssociationStudentCharacteristics. Reflects important characteristics of a student. If a student has a characteristic present, that characteristic is considered true or active for that student. If a characteristic is not present, no assumption is made as to the applicability of the characteristic, but local policy may dictate otherwise.")

  public List<EdFiStudentEducationOrganizationAssociationStudentCharacteristic> getStudentCharacteristics() {
    return studentCharacteristics;
  }


  public void setStudentCharacteristics(List<EdFiStudentEducationOrganizationAssociationStudentCharacteristic> studentCharacteristics) {
    this.studentCharacteristics = studentCharacteristics;
  }


  public EdFiStudentEducationOrganizationAssociation studentIdentificationCodes(List<EdFiStudentEducationOrganizationAssociationStudentIdentificationCode> studentIdentificationCodes) {
    
    this.studentIdentificationCodes = studentIdentificationCodes;
    return this;
  }

  public EdFiStudentEducationOrganizationAssociation addStudentIdentificationCodesItem(EdFiStudentEducationOrganizationAssociationStudentIdentificationCode studentIdentificationCodesItem) {
    if (this.studentIdentificationCodes == null) {
      this.studentIdentificationCodes = new ArrayList<EdFiStudentEducationOrganizationAssociationStudentIdentificationCode>();
    }
    this.studentIdentificationCodes.add(studentIdentificationCodesItem);
    return this;
  }

   /**
   * An unordered collection of studentEducationOrganizationAssociationStudentIdentificationCodes. A coding scheme that is used for identification and record-keeping purposes by schools, social services, or other agencies to refer to a student.
   * @return studentIdentificationCodes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An unordered collection of studentEducationOrganizationAssociationStudentIdentificationCodes. A coding scheme that is used for identification and record-keeping purposes by schools, social services, or other agencies to refer to a student.")

  public List<EdFiStudentEducationOrganizationAssociationStudentIdentificationCode> getStudentIdentificationCodes() {
    return studentIdentificationCodes;
  }


  public void setStudentIdentificationCodes(List<EdFiStudentEducationOrganizationAssociationStudentIdentificationCode> studentIdentificationCodes) {
    this.studentIdentificationCodes = studentIdentificationCodes;
  }


  public EdFiStudentEducationOrganizationAssociation studentIndicators(List<EdFiStudentEducationOrganizationAssociationStudentIndicator> studentIndicators) {
    
    this.studentIndicators = studentIndicators;
    return this;
  }

  public EdFiStudentEducationOrganizationAssociation addStudentIndicatorsItem(EdFiStudentEducationOrganizationAssociationStudentIndicator studentIndicatorsItem) {
    if (this.studentIndicators == null) {
      this.studentIndicators = new ArrayList<EdFiStudentEducationOrganizationAssociationStudentIndicator>();
    }
    this.studentIndicators.add(studentIndicatorsItem);
    return this;
  }

   /**
   * An unordered collection of studentEducationOrganizationAssociationStudentIndicators. An indicator or metric computed for the student (e.g., at risk).
   * @return studentIndicators
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An unordered collection of studentEducationOrganizationAssociationStudentIndicators. An indicator or metric computed for the student (e.g., at risk).")

  public List<EdFiStudentEducationOrganizationAssociationStudentIndicator> getStudentIndicators() {
    return studentIndicators;
  }


  public void setStudentIndicators(List<EdFiStudentEducationOrganizationAssociationStudentIndicator> studentIndicators) {
    this.studentIndicators = studentIndicators;
  }


  public EdFiStudentEducationOrganizationAssociation telephones(List<EdFiStudentEducationOrganizationAssociationTelephone> telephones) {
    
    this.telephones = telephones;
    return this;
  }

  public EdFiStudentEducationOrganizationAssociation addTelephonesItem(EdFiStudentEducationOrganizationAssociationTelephone telephonesItem) {
    if (this.telephones == null) {
      this.telephones = new ArrayList<EdFiStudentEducationOrganizationAssociationTelephone>();
    }
    this.telephones.add(telephonesItem);
    return this;
  }

   /**
   * An unordered collection of studentEducationOrganizationAssociationTelephones. The 10-digit telephone number, including the area code, for the person.
   * @return telephones
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An unordered collection of studentEducationOrganizationAssociationTelephones. The 10-digit telephone number, including the area code, for the person.")

  public List<EdFiStudentEducationOrganizationAssociationTelephone> getTelephones() {
    return telephones;
  }


  public void setTelephones(List<EdFiStudentEducationOrganizationAssociationTelephone> telephones) {
    this.telephones = telephones;
  }


  public EdFiStudentEducationOrganizationAssociation tribalAffiliations(List<EdFiStudentEducationOrganizationAssociationTribalAffiliation> tribalAffiliations) {
    
    this.tribalAffiliations = tribalAffiliations;
    return this;
  }

  public EdFiStudentEducationOrganizationAssociation addTribalAffiliationsItem(EdFiStudentEducationOrganizationAssociationTribalAffiliation tribalAffiliationsItem) {
    if (this.tribalAffiliations == null) {
      this.tribalAffiliations = new ArrayList<EdFiStudentEducationOrganizationAssociationTribalAffiliation>();
    }
    this.tribalAffiliations.add(tribalAffiliationsItem);
    return this;
  }

   /**
   * An unordered collection of studentEducationOrganizationAssociationTribalAffiliations. An American Indian tribe with which the student is affiliated as last reported to the education organization.
   * @return tribalAffiliations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An unordered collection of studentEducationOrganizationAssociationTribalAffiliations. An American Indian tribe with which the student is affiliated as last reported to the education organization.")

  public List<EdFiStudentEducationOrganizationAssociationTribalAffiliation> getTribalAffiliations() {
    return tribalAffiliations;
  }


  public void setTribalAffiliations(List<EdFiStudentEducationOrganizationAssociationTribalAffiliation> tribalAffiliations) {
    this.tribalAffiliations = tribalAffiliations;
  }


  public EdFiStudentEducationOrganizationAssociation etag(String etag) {
    
    this.etag = etag;
    return this;
  }

   /**
   * A unique system-generated value that identifies the version of the resource.
   * @return etag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A unique system-generated value that identifies the version of the resource.")

  public String getEtag() {
    return etag;
  }


  public void setEtag(String etag) {
    this.etag = etag;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EdFiStudentEducationOrganizationAssociation edFiStudentEducationOrganizationAssociation = (EdFiStudentEducationOrganizationAssociation) o;
    return Objects.equals(this.id, edFiStudentEducationOrganizationAssociation.id) &&
        Objects.equals(this.educationOrganizationReference, edFiStudentEducationOrganizationAssociation.educationOrganizationReference) &&
        Objects.equals(this.studentReference, edFiStudentEducationOrganizationAssociation.studentReference) &&
        Objects.equals(this.addresses, edFiStudentEducationOrganizationAssociation.addresses) &&
        Objects.equals(this.ancestryEthnicOrigins, edFiStudentEducationOrganizationAssociation.ancestryEthnicOrigins) &&
        Objects.equals(this.cohortYears, edFiStudentEducationOrganizationAssociation.cohortYears) &&
        Objects.equals(this.disabilities, edFiStudentEducationOrganizationAssociation.disabilities) &&
        Objects.equals(this.electronicMails, edFiStudentEducationOrganizationAssociation.electronicMails) &&
        Objects.equals(this.hispanicLatinoEthnicity, edFiStudentEducationOrganizationAssociation.hispanicLatinoEthnicity) &&
        Objects.equals(this.internationalAddresses, edFiStudentEducationOrganizationAssociation.internationalAddresses) &&
        Objects.equals(this.languages, edFiStudentEducationOrganizationAssociation.languages) &&
        Objects.equals(this.limitedEnglishProficiencyDescriptor, edFiStudentEducationOrganizationAssociation.limitedEnglishProficiencyDescriptor) &&
        Objects.equals(this.loginId, edFiStudentEducationOrganizationAssociation.loginId) &&
        Objects.equals(this.oldEthnicityDescriptor, edFiStudentEducationOrganizationAssociation.oldEthnicityDescriptor) &&
        Objects.equals(this.profileThumbnail, edFiStudentEducationOrganizationAssociation.profileThumbnail) &&
        Objects.equals(this.programParticipations, edFiStudentEducationOrganizationAssociation.programParticipations) &&
        Objects.equals(this.races, edFiStudentEducationOrganizationAssociation.races) &&
        Objects.equals(this.sexDescriptor, edFiStudentEducationOrganizationAssociation.sexDescriptor) &&
        Objects.equals(this.studentCharacteristics, edFiStudentEducationOrganizationAssociation.studentCharacteristics) &&
        Objects.equals(this.studentIdentificationCodes, edFiStudentEducationOrganizationAssociation.studentIdentificationCodes) &&
        Objects.equals(this.studentIndicators, edFiStudentEducationOrganizationAssociation.studentIndicators) &&
        Objects.equals(this.telephones, edFiStudentEducationOrganizationAssociation.telephones) &&
        Objects.equals(this.tribalAffiliations, edFiStudentEducationOrganizationAssociation.tribalAffiliations) &&
        Objects.equals(this.etag, edFiStudentEducationOrganizationAssociation.etag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, educationOrganizationReference, studentReference, addresses, ancestryEthnicOrigins, cohortYears, disabilities, electronicMails, hispanicLatinoEthnicity, internationalAddresses, languages, limitedEnglishProficiencyDescriptor, loginId, oldEthnicityDescriptor, profileThumbnail, programParticipations, races, sexDescriptor, studentCharacteristics, studentIdentificationCodes, studentIndicators, telephones, tribalAffiliations, etag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EdFiStudentEducationOrganizationAssociation {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    educationOrganizationReference: ").append(toIndentedString(educationOrganizationReference)).append("\n");
    sb.append("    studentReference: ").append(toIndentedString(studentReference)).append("\n");
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("    ancestryEthnicOrigins: ").append(toIndentedString(ancestryEthnicOrigins)).append("\n");
    sb.append("    cohortYears: ").append(toIndentedString(cohortYears)).append("\n");
    sb.append("    disabilities: ").append(toIndentedString(disabilities)).append("\n");
    sb.append("    electronicMails: ").append(toIndentedString(electronicMails)).append("\n");
    sb.append("    hispanicLatinoEthnicity: ").append(toIndentedString(hispanicLatinoEthnicity)).append("\n");
    sb.append("    internationalAddresses: ").append(toIndentedString(internationalAddresses)).append("\n");
    sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
    sb.append("    limitedEnglishProficiencyDescriptor: ").append(toIndentedString(limitedEnglishProficiencyDescriptor)).append("\n");
    sb.append("    loginId: ").append(toIndentedString(loginId)).append("\n");
    sb.append("    oldEthnicityDescriptor: ").append(toIndentedString(oldEthnicityDescriptor)).append("\n");
    sb.append("    profileThumbnail: ").append(toIndentedString(profileThumbnail)).append("\n");
    sb.append("    programParticipations: ").append(toIndentedString(programParticipations)).append("\n");
    sb.append("    races: ").append(toIndentedString(races)).append("\n");
    sb.append("    sexDescriptor: ").append(toIndentedString(sexDescriptor)).append("\n");
    sb.append("    studentCharacteristics: ").append(toIndentedString(studentCharacteristics)).append("\n");
    sb.append("    studentIdentificationCodes: ").append(toIndentedString(studentIdentificationCodes)).append("\n");
    sb.append("    studentIndicators: ").append(toIndentedString(studentIndicators)).append("\n");
    sb.append("    telephones: ").append(toIndentedString(telephones)).append("\n");
    sb.append("    tribalAffiliations: ").append(toIndentedString(tribalAffiliations)).append("\n");
    sb.append("    etag: ").append(toIndentedString(etag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

