/*
 * Ed-Fi Operational Data Store API
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Models.Resources;

import java.util.Objects;
import java.util.Arrays;
import Models.Resources.Link;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * TpdmRecruitmentEventAttendanceReference
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-28T14:58:32.034-05:00[America/Mexico_City]")
public class TpdmRecruitmentEventAttendanceReference {
  public static final String SERIALIZED_NAME_EDUCATION_ORGANIZATION_ID = "educationOrganizationId";
  @SerializedName(SERIALIZED_NAME_EDUCATION_ORGANIZATION_ID)
  private Integer educationOrganizationId;

  public static final String SERIALIZED_NAME_EVENT_DATE = "eventDate";
  @SerializedName(SERIALIZED_NAME_EVENT_DATE)
  private LocalDate eventDate;

  public static final String SERIALIZED_NAME_EVENT_TITLE = "eventTitle";
  @SerializedName(SERIALIZED_NAME_EVENT_TITLE)
  private String eventTitle;

  public static final String SERIALIZED_NAME_RECRUITMENT_EVENT_ATTENDEE_IDENTIFIER = "recruitmentEventAttendeeIdentifier";
  @SerializedName(SERIALIZED_NAME_RECRUITMENT_EVENT_ATTENDEE_IDENTIFIER)
  private String recruitmentEventAttendeeIdentifier;

  public static final String SERIALIZED_NAME_LINK = "link";
  @SerializedName(SERIALIZED_NAME_LINK)
  private Link link;

  public TpdmRecruitmentEventAttendanceReference() { 
  }

  public TpdmRecruitmentEventAttendanceReference educationOrganizationId(Integer educationOrganizationId) {
    
    this.educationOrganizationId = educationOrganizationId;
    return this;
  }

   /**
   * The identifier assigned to an education organization.
   * @return educationOrganizationId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The identifier assigned to an education organization.")

  public Integer getEducationOrganizationId() {
    return educationOrganizationId;
  }


  public void setEducationOrganizationId(Integer educationOrganizationId) {
    this.educationOrganizationId = educationOrganizationId;
  }


  public TpdmRecruitmentEventAttendanceReference eventDate(LocalDate eventDate) {
    
    this.eventDate = eventDate;
    return this;
  }

   /**
   * The date of the event.
   * @return eventDate
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The date of the event.")

  public LocalDate getEventDate() {
    return eventDate;
  }


  public void setEventDate(LocalDate eventDate) {
    this.eventDate = eventDate;
  }


  public TpdmRecruitmentEventAttendanceReference eventTitle(String eventTitle) {
    
    this.eventTitle = eventTitle;
    return this;
  }

   /**
   * The title of the event.
   * @return eventTitle
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The title of the event.")

  public String getEventTitle() {
    return eventTitle;
  }


  public void setEventTitle(String eventTitle) {
    this.eventTitle = eventTitle;
  }


  public TpdmRecruitmentEventAttendanceReference recruitmentEventAttendeeIdentifier(String recruitmentEventAttendeeIdentifier) {
    
    this.recruitmentEventAttendeeIdentifier = recruitmentEventAttendeeIdentifier;
    return this;
  }

   /**
   * The identifier for the attendee to a recuitment event.
   * @return recruitmentEventAttendeeIdentifier
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The identifier for the attendee to a recuitment event.")

  public String getRecruitmentEventAttendeeIdentifier() {
    return recruitmentEventAttendeeIdentifier;
  }


  public void setRecruitmentEventAttendeeIdentifier(String recruitmentEventAttendeeIdentifier) {
    this.recruitmentEventAttendeeIdentifier = recruitmentEventAttendeeIdentifier;
  }


  public TpdmRecruitmentEventAttendanceReference link(Link link) {
    
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Link getLink() {
    return link;
  }


  public void setLink(Link link) {
    this.link = link;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TpdmRecruitmentEventAttendanceReference tpdmRecruitmentEventAttendanceReference = (TpdmRecruitmentEventAttendanceReference) o;
    return Objects.equals(this.educationOrganizationId, tpdmRecruitmentEventAttendanceReference.educationOrganizationId) &&
        Objects.equals(this.eventDate, tpdmRecruitmentEventAttendanceReference.eventDate) &&
        Objects.equals(this.eventTitle, tpdmRecruitmentEventAttendanceReference.eventTitle) &&
        Objects.equals(this.recruitmentEventAttendeeIdentifier, tpdmRecruitmentEventAttendanceReference.recruitmentEventAttendeeIdentifier) &&
        Objects.equals(this.link, tpdmRecruitmentEventAttendanceReference.link);
  }

  @Override
  public int hashCode() {
    return Objects.hash(educationOrganizationId, eventDate, eventTitle, recruitmentEventAttendeeIdentifier, link);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TpdmRecruitmentEventAttendanceReference {\n");
    sb.append("    educationOrganizationId: ").append(toIndentedString(educationOrganizationId)).append("\n");
    sb.append("    eventDate: ").append(toIndentedString(eventDate)).append("\n");
    sb.append("    eventTitle: ").append(toIndentedString(eventTitle)).append("\n");
    sb.append("    recruitmentEventAttendeeIdentifier: ").append(toIndentedString(recruitmentEventAttendeeIdentifier)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

