/*
 * Ed-Fi Operational Data Store API
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Models.Resources;

import java.util.Objects;
import java.util.Arrays;
import Models.Resources.EdFiOpenStaffPositionReference;
import Models.Resources.TpdmStaffEducatorPreparationProgram;
import Models.Resources.TpdmStaffEducatorResearch;
import Models.Resources.TpdmStaffHighlyQualifiedAcademicSubject;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * TpdmStaffExtension
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-28T14:58:32.034-05:00[America/Mexico_City]")
public class TpdmStaffExtension {
  public static final String SERIALIZED_NAME_GENDER_DESCRIPTOR = "genderDescriptor";
  @SerializedName(SERIALIZED_NAME_GENDER_DESCRIPTOR)
  private String genderDescriptor;

  public static final String SERIALIZED_NAME_OPEN_STAFF_POSITION_REFERENCE = "openStaffPositionReference";
  @SerializedName(SERIALIZED_NAME_OPEN_STAFF_POSITION_REFERENCE)
  private EdFiOpenStaffPositionReference openStaffPositionReference;

  public static final String SERIALIZED_NAME_EDUCATOR_PREPARATION_PROGRAMS = "educatorPreparationPrograms";
  @SerializedName(SERIALIZED_NAME_EDUCATOR_PREPARATION_PROGRAMS)
  private List<TpdmStaffEducatorPreparationProgram> educatorPreparationPrograms = null;

  public static final String SERIALIZED_NAME_HIGHLY_QUALIFIED_ACADEMIC_SUBJECTS = "highlyQualifiedAcademicSubjects";
  @SerializedName(SERIALIZED_NAME_HIGHLY_QUALIFIED_ACADEMIC_SUBJECTS)
  private List<TpdmStaffHighlyQualifiedAcademicSubject> highlyQualifiedAcademicSubjects = null;

  public static final String SERIALIZED_NAME_EDUCATOR_RESEARCH = "educatorResearch";
  @SerializedName(SERIALIZED_NAME_EDUCATOR_RESEARCH)
  private TpdmStaffEducatorResearch educatorResearch;

  public TpdmStaffExtension() { 
  }

  public TpdmStaffExtension genderDescriptor(String genderDescriptor) {
    
    this.genderDescriptor = genderDescriptor;
    return this;
  }

   /**
   * The gender with which a person associates.
   * @return genderDescriptor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The gender with which a person associates.")

  public String getGenderDescriptor() {
    return genderDescriptor;
  }


  public void setGenderDescriptor(String genderDescriptor) {
    this.genderDescriptor = genderDescriptor;
  }


  public TpdmStaffExtension openStaffPositionReference(EdFiOpenStaffPositionReference openStaffPositionReference) {
    
    this.openStaffPositionReference = openStaffPositionReference;
    return this;
  }

   /**
   * Get openStaffPositionReference
   * @return openStaffPositionReference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EdFiOpenStaffPositionReference getOpenStaffPositionReference() {
    return openStaffPositionReference;
  }


  public void setOpenStaffPositionReference(EdFiOpenStaffPositionReference openStaffPositionReference) {
    this.openStaffPositionReference = openStaffPositionReference;
  }


  public TpdmStaffExtension educatorPreparationPrograms(List<TpdmStaffEducatorPreparationProgram> educatorPreparationPrograms) {
    
    this.educatorPreparationPrograms = educatorPreparationPrograms;
    return this;
  }

  public TpdmStaffExtension addEducatorPreparationProgramsItem(TpdmStaffEducatorPreparationProgram educatorPreparationProgramsItem) {
    if (this.educatorPreparationPrograms == null) {
      this.educatorPreparationPrograms = new ArrayList<TpdmStaffEducatorPreparationProgram>();
    }
    this.educatorPreparationPrograms.add(educatorPreparationProgramsItem);
    return this;
  }

   /**
   * An unordered collection of staffEducatorPreparationPrograms. The Educator Preparation Program(s) completed by the teacher.
   * @return educatorPreparationPrograms
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An unordered collection of staffEducatorPreparationPrograms. The Educator Preparation Program(s) completed by the teacher.")

  public List<TpdmStaffEducatorPreparationProgram> getEducatorPreparationPrograms() {
    return educatorPreparationPrograms;
  }


  public void setEducatorPreparationPrograms(List<TpdmStaffEducatorPreparationProgram> educatorPreparationPrograms) {
    this.educatorPreparationPrograms = educatorPreparationPrograms;
  }


  public TpdmStaffExtension highlyQualifiedAcademicSubjects(List<TpdmStaffHighlyQualifiedAcademicSubject> highlyQualifiedAcademicSubjects) {
    
    this.highlyQualifiedAcademicSubjects = highlyQualifiedAcademicSubjects;
    return this;
  }

  public TpdmStaffExtension addHighlyQualifiedAcademicSubjectsItem(TpdmStaffHighlyQualifiedAcademicSubject highlyQualifiedAcademicSubjectsItem) {
    if (this.highlyQualifiedAcademicSubjects == null) {
      this.highlyQualifiedAcademicSubjects = new ArrayList<TpdmStaffHighlyQualifiedAcademicSubject>();
    }
    this.highlyQualifiedAcademicSubjects.add(highlyQualifiedAcademicSubjectsItem);
    return this;
  }

   /**
   * An unordered collection of staffHighlyQualifiedAcademicSubjects. The academic subject(s) in which the staff is deemed to be \&quot;highly qualified\&quot;.
   * @return highlyQualifiedAcademicSubjects
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An unordered collection of staffHighlyQualifiedAcademicSubjects. The academic subject(s) in which the staff is deemed to be \"highly qualified\".")

  public List<TpdmStaffHighlyQualifiedAcademicSubject> getHighlyQualifiedAcademicSubjects() {
    return highlyQualifiedAcademicSubjects;
  }


  public void setHighlyQualifiedAcademicSubjects(List<TpdmStaffHighlyQualifiedAcademicSubject> highlyQualifiedAcademicSubjects) {
    this.highlyQualifiedAcademicSubjects = highlyQualifiedAcademicSubjects;
  }


  public TpdmStaffExtension educatorResearch(TpdmStaffEducatorResearch educatorResearch) {
    
    this.educatorResearch = educatorResearch;
    return this;
  }

   /**
   * Get educatorResearch
   * @return educatorResearch
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TpdmStaffEducatorResearch getEducatorResearch() {
    return educatorResearch;
  }


  public void setEducatorResearch(TpdmStaffEducatorResearch educatorResearch) {
    this.educatorResearch = educatorResearch;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TpdmStaffExtension tpdmStaffExtension = (TpdmStaffExtension) o;
    return Objects.equals(this.genderDescriptor, tpdmStaffExtension.genderDescriptor) &&
        Objects.equals(this.openStaffPositionReference, tpdmStaffExtension.openStaffPositionReference) &&
        Objects.equals(this.educatorPreparationPrograms, tpdmStaffExtension.educatorPreparationPrograms) &&
        Objects.equals(this.highlyQualifiedAcademicSubjects, tpdmStaffExtension.highlyQualifiedAcademicSubjects) &&
        Objects.equals(this.educatorResearch, tpdmStaffExtension.educatorResearch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(genderDescriptor, openStaffPositionReference, educatorPreparationPrograms, highlyQualifiedAcademicSubjects, educatorResearch);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TpdmStaffExtension {\n");
    sb.append("    genderDescriptor: ").append(toIndentedString(genderDescriptor)).append("\n");
    sb.append("    openStaffPositionReference: ").append(toIndentedString(openStaffPositionReference)).append("\n");
    sb.append("    educatorPreparationPrograms: ").append(toIndentedString(educatorPreparationPrograms)).append("\n");
    sb.append("    highlyQualifiedAcademicSubjects: ").append(toIndentedString(highlyQualifiedAcademicSubjects)).append("\n");
    sb.append("    educatorResearch: ").append(toIndentedString(educatorResearch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

