/*
 * Ed-Fi Operational Data Store API
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Models.Resources;

import java.util.Objects;
import java.util.Arrays;
import Models.Resources.TpdmEvaluationElementRatingResult;
import Models.Resources.TpdmEvaluationElementReference;
import Models.Resources.TpdmEvaluationObjectiveRatingReference;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * TpdmEvaluationElementRating
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-06-28T14:58:32.034-05:00[America/Mexico_City]")
public class TpdmEvaluationElementRating {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_EVALUATION_ELEMENT_REFERENCE = "evaluationElementReference";
  @SerializedName(SERIALIZED_NAME_EVALUATION_ELEMENT_REFERENCE)
  private TpdmEvaluationElementReference evaluationElementReference;

  public static final String SERIALIZED_NAME_EVALUATION_OBJECTIVE_RATING_REFERENCE = "evaluationObjectiveRatingReference";
  @SerializedName(SERIALIZED_NAME_EVALUATION_OBJECTIVE_RATING_REFERENCE)
  private TpdmEvaluationObjectiveRatingReference evaluationObjectiveRatingReference;

  public static final String SERIALIZED_NAME_AREA_OF_REFINEMENT = "areaOfRefinement";
  @SerializedName(SERIALIZED_NAME_AREA_OF_REFINEMENT)
  private String areaOfRefinement;

  public static final String SERIALIZED_NAME_AREA_OF_REINFORCEMENT = "areaOfReinforcement";
  @SerializedName(SERIALIZED_NAME_AREA_OF_REINFORCEMENT)
  private String areaOfReinforcement;

  public static final String SERIALIZED_NAME_COMMENTS = "comments";
  @SerializedName(SERIALIZED_NAME_COMMENTS)
  private String comments;

  public static final String SERIALIZED_NAME_EVALUATION_ELEMENT_RATING_LEVEL_DESCRIPTOR = "evaluationElementRatingLevelDescriptor";
  @SerializedName(SERIALIZED_NAME_EVALUATION_ELEMENT_RATING_LEVEL_DESCRIPTOR)
  private String evaluationElementRatingLevelDescriptor;

  public static final String SERIALIZED_NAME_FEEDBACK = "feedback";
  @SerializedName(SERIALIZED_NAME_FEEDBACK)
  private String feedback;

  public static final String SERIALIZED_NAME_RESULTS = "results";
  @SerializedName(SERIALIZED_NAME_RESULTS)
  private List<TpdmEvaluationElementRatingResult> results = null;

  public static final String SERIALIZED_NAME_ETAG = "_etag";
  @SerializedName(SERIALIZED_NAME_ETAG)
  private String etag;

  public TpdmEvaluationElementRating() { 
  }

  public TpdmEvaluationElementRating id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public TpdmEvaluationElementRating evaluationElementReference(TpdmEvaluationElementReference evaluationElementReference) {
    
    this.evaluationElementReference = evaluationElementReference;
    return this;
  }

   /**
   * Get evaluationElementReference
   * @return evaluationElementReference
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public TpdmEvaluationElementReference getEvaluationElementReference() {
    return evaluationElementReference;
  }


  public void setEvaluationElementReference(TpdmEvaluationElementReference evaluationElementReference) {
    this.evaluationElementReference = evaluationElementReference;
  }


  public TpdmEvaluationElementRating evaluationObjectiveRatingReference(TpdmEvaluationObjectiveRatingReference evaluationObjectiveRatingReference) {
    
    this.evaluationObjectiveRatingReference = evaluationObjectiveRatingReference;
    return this;
  }

   /**
   * Get evaluationObjectiveRatingReference
   * @return evaluationObjectiveRatingReference
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public TpdmEvaluationObjectiveRatingReference getEvaluationObjectiveRatingReference() {
    return evaluationObjectiveRatingReference;
  }


  public void setEvaluationObjectiveRatingReference(TpdmEvaluationObjectiveRatingReference evaluationObjectiveRatingReference) {
    this.evaluationObjectiveRatingReference = evaluationObjectiveRatingReference;
  }


  public TpdmEvaluationElementRating areaOfRefinement(String areaOfRefinement) {
    
    this.areaOfRefinement = areaOfRefinement;
    return this;
  }

   /**
   * Area(s) identified for person to refine or improve as part of the evaluation.
   * @return areaOfRefinement
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Area(s) identified for person to refine or improve as part of the evaluation.")

  public String getAreaOfRefinement() {
    return areaOfRefinement;
  }


  public void setAreaOfRefinement(String areaOfRefinement) {
    this.areaOfRefinement = areaOfRefinement;
  }


  public TpdmEvaluationElementRating areaOfReinforcement(String areaOfReinforcement) {
    
    this.areaOfReinforcement = areaOfReinforcement;
    return this;
  }

   /**
   * Area(s) identified for reinforcement or positive feedback as part of the evaluation.
   * @return areaOfReinforcement
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Area(s) identified for reinforcement or positive feedback as part of the evaluation.")

  public String getAreaOfReinforcement() {
    return areaOfReinforcement;
  }


  public void setAreaOfReinforcement(String areaOfReinforcement) {
    this.areaOfReinforcement = areaOfReinforcement;
  }


  public TpdmEvaluationElementRating comments(String comments) {
    
    this.comments = comments;
    return this;
  }

   /**
   * Any comments about the performance evaluation to be captured.
   * @return comments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Any comments about the performance evaluation to be captured.")

  public String getComments() {
    return comments;
  }


  public void setComments(String comments) {
    this.comments = comments;
  }


  public TpdmEvaluationElementRating evaluationElementRatingLevelDescriptor(String evaluationElementRatingLevelDescriptor) {
    
    this.evaluationElementRatingLevelDescriptor = evaluationElementRatingLevelDescriptor;
    return this;
  }

   /**
   * The rating level achieved based upon the rating or score.
   * @return evaluationElementRatingLevelDescriptor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The rating level achieved based upon the rating or score.")

  public String getEvaluationElementRatingLevelDescriptor() {
    return evaluationElementRatingLevelDescriptor;
  }


  public void setEvaluationElementRatingLevelDescriptor(String evaluationElementRatingLevelDescriptor) {
    this.evaluationElementRatingLevelDescriptor = evaluationElementRatingLevelDescriptor;
  }


  public TpdmEvaluationElementRating feedback(String feedback) {
    
    this.feedback = feedback;
    return this;
  }

   /**
   * Feedback provided to the evaluated person.
   * @return feedback
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Feedback provided to the evaluated person.")

  public String getFeedback() {
    return feedback;
  }


  public void setFeedback(String feedback) {
    this.feedback = feedback;
  }


  public TpdmEvaluationElementRating results(List<TpdmEvaluationElementRatingResult> results) {
    
    this.results = results;
    return this;
  }

  public TpdmEvaluationElementRating addResultsItem(TpdmEvaluationElementRatingResult resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<TpdmEvaluationElementRatingResult>();
    }
    this.results.add(resultsItem);
    return this;
  }

   /**
   * An unordered collection of evaluationElementRatingResults. The numerical summary rating or score for the evaluation element.
   * @return results
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An unordered collection of evaluationElementRatingResults. The numerical summary rating or score for the evaluation element.")

  public List<TpdmEvaluationElementRatingResult> getResults() {
    return results;
  }


  public void setResults(List<TpdmEvaluationElementRatingResult> results) {
    this.results = results;
  }


  public TpdmEvaluationElementRating etag(String etag) {
    
    this.etag = etag;
    return this;
  }

   /**
   * A unique system-generated value that identifies the version of the resource.
   * @return etag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A unique system-generated value that identifies the version of the resource.")

  public String getEtag() {
    return etag;
  }


  public void setEtag(String etag) {
    this.etag = etag;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TpdmEvaluationElementRating tpdmEvaluationElementRating = (TpdmEvaluationElementRating) o;
    return Objects.equals(this.id, tpdmEvaluationElementRating.id) &&
        Objects.equals(this.evaluationElementReference, tpdmEvaluationElementRating.evaluationElementReference) &&
        Objects.equals(this.evaluationObjectiveRatingReference, tpdmEvaluationElementRating.evaluationObjectiveRatingReference) &&
        Objects.equals(this.areaOfRefinement, tpdmEvaluationElementRating.areaOfRefinement) &&
        Objects.equals(this.areaOfReinforcement, tpdmEvaluationElementRating.areaOfReinforcement) &&
        Objects.equals(this.comments, tpdmEvaluationElementRating.comments) &&
        Objects.equals(this.evaluationElementRatingLevelDescriptor, tpdmEvaluationElementRating.evaluationElementRatingLevelDescriptor) &&
        Objects.equals(this.feedback, tpdmEvaluationElementRating.feedback) &&
        Objects.equals(this.results, tpdmEvaluationElementRating.results) &&
        Objects.equals(this.etag, tpdmEvaluationElementRating.etag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, evaluationElementReference, evaluationObjectiveRatingReference, areaOfRefinement, areaOfReinforcement, comments, evaluationElementRatingLevelDescriptor, feedback, results, etag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TpdmEvaluationElementRating {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    evaluationElementReference: ").append(toIndentedString(evaluationElementReference)).append("\n");
    sb.append("    evaluationObjectiveRatingReference: ").append(toIndentedString(evaluationObjectiveRatingReference)).append("\n");
    sb.append("    areaOfRefinement: ").append(toIndentedString(areaOfRefinement)).append("\n");
    sb.append("    areaOfReinforcement: ").append(toIndentedString(areaOfReinforcement)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    evaluationElementRatingLevelDescriptor: ").append(toIndentedString(evaluationElementRatingLevelDescriptor)).append("\n");
    sb.append("    feedback: ").append(toIndentedString(feedback)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    etag: ").append(toIndentedString(etag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

