/*
 * Ed-Fi Operational Data Store API
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Api.Resources;

import Api.ApiCallback;
import Api.ApiClient;
import Api.ApiException;
import Api.ApiResponse;
import Api.Configuration;
import Api.Pair;
import Api.ProgressRequestBody;
import Api.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import Models.Resources.DeletedResource;
import Models.Resources.EdFiStaffSchoolAssociation;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class StaffSchoolAssociationsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public StaffSchoolAssociationsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public StaffSchoolAssociationsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for deleteStaffSchoolAssociationById
     * @param id A resource identifier that uniquely identifies the resource. (required)
     * @param ifMatch The ETag header value used to prevent the DELETE from removing a resource modified by another consumer. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> The resource was successfully deleted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Is Not Allowed. When the Snapshot-Identifier header is present the method is not allowed. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict.  The request cannot be completed because it would result in an invalid state.  See the response body for details. </td><td>  -  </td></tr>
        <tr><td> 412 </td><td> The resource&#39;s current server-side ETag value does not match the supplied If-Match header value in the request. This indicates the resource has been modified by another consumer. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteStaffSchoolAssociationByIdCall(String id, String ifMatch, final ApiCallback _callback) throws ApiException {
        String basePath = null;

        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/ed-fi/staffSchoolAssociations/{id}"
            .replaceAll("\\{" + "id" + "\\}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (ifMatch != null) {
            localVarHeaderParams.put("If-Match", localVarApiClient.parameterToString(ifMatch));
        }

        final String[] localVarAccepts = {
            
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2_client_credentials" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteStaffSchoolAssociationByIdValidateBeforeCall(String id, String ifMatch, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deleteStaffSchoolAssociationById(Async)");
        }
        

        okhttp3.Call localVarCall = deleteStaffSchoolAssociationByIdCall(id, ifMatch, _callback);
        return localVarCall;

    }

    /**
     * Deletes an existing resource using the resource identifier.
     * The DELETE operation is used to delete an existing resource by identifier. If the resource doesn&#39;t exist, an error will result (the resource will not be found).
     * @param id A resource identifier that uniquely identifies the resource. (required)
     * @param ifMatch The ETag header value used to prevent the DELETE from removing a resource modified by another consumer. (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> The resource was successfully deleted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Is Not Allowed. When the Snapshot-Identifier header is present the method is not allowed. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict.  The request cannot be completed because it would result in an invalid state.  See the response body for details. </td><td>  -  </td></tr>
        <tr><td> 412 </td><td> The resource&#39;s current server-side ETag value does not match the supplied If-Match header value in the request. This indicates the resource has been modified by another consumer. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public void deleteStaffSchoolAssociationById(String id, String ifMatch) throws ApiException {
        deleteStaffSchoolAssociationByIdWithHttpInfo(id, ifMatch);
    }

    /**
     * Deletes an existing resource using the resource identifier.
     * The DELETE operation is used to delete an existing resource by identifier. If the resource doesn&#39;t exist, an error will result (the resource will not be found).
     * @param id A resource identifier that uniquely identifies the resource. (required)
     * @param ifMatch The ETag header value used to prevent the DELETE from removing a resource modified by another consumer. (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> The resource was successfully deleted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Is Not Allowed. When the Snapshot-Identifier header is present the method is not allowed. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict.  The request cannot be completed because it would result in an invalid state.  See the response body for details. </td><td>  -  </td></tr>
        <tr><td> 412 </td><td> The resource&#39;s current server-side ETag value does not match the supplied If-Match header value in the request. This indicates the resource has been modified by another consumer. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deleteStaffSchoolAssociationByIdWithHttpInfo(String id, String ifMatch) throws ApiException {
        okhttp3.Call localVarCall = deleteStaffSchoolAssociationByIdValidateBeforeCall(id, ifMatch, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Deletes an existing resource using the resource identifier. (asynchronously)
     * The DELETE operation is used to delete an existing resource by identifier. If the resource doesn&#39;t exist, an error will result (the resource will not be found).
     * @param id A resource identifier that uniquely identifies the resource. (required)
     * @param ifMatch The ETag header value used to prevent the DELETE from removing a resource modified by another consumer. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> The resource was successfully deleted. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Is Not Allowed. When the Snapshot-Identifier header is present the method is not allowed. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict.  The request cannot be completed because it would result in an invalid state.  See the response body for details. </td><td>  -  </td></tr>
        <tr><td> 412 </td><td> The resource&#39;s current server-side ETag value does not match the supplied If-Match header value in the request. This indicates the resource has been modified by another consumer. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteStaffSchoolAssociationByIdAsync(String id, String ifMatch, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteStaffSchoolAssociationByIdValidateBeforeCall(id, ifMatch, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for deletesStaffSchoolAssociations
     * @param offset Indicates how many items should be skipped before returning results. (optional, default to 0)
     * @param limit Indicates the maximum number of items that should be returned in the results. (optional, default to 25)
     * @param minChangeVersion Used in synchronization to set sequence minimum ChangeVersion (optional)
     * @param maxChangeVersion Used in synchronization to set sequence maximum ChangeVersion (optional)
     * @param snapshotIdentifier Indicates the Snapshot-Identifier that should be used. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The requested resource was successfully retrieved. </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> The resource&#39;s current server-side ETag value matched the If-None-Match header value supplied with the request indicating the resource has not been modified. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 410 </td><td> Gone. An attempt to connect to the database for the snapshot specified by the Snapshot-Identifier header was unsuccessful (indicating the snapshot may have been removed). </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deletesStaffSchoolAssociationsCall(Integer offset, Integer limit, Integer minChangeVersion, Integer maxChangeVersion, String snapshotIdentifier, final ApiCallback _callback) throws ApiException {
        String basePath = null;

        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/ed-fi/staffSchoolAssociations/deletes";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (minChangeVersion != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("minChangeVersion", minChangeVersion));
        }

        if (maxChangeVersion != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("maxChangeVersion", maxChangeVersion));
        }

        if (snapshotIdentifier != null) {
            localVarHeaderParams.put("Snapshot-Identifier", localVarApiClient.parameterToString(snapshotIdentifier));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2_client_credentials" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deletesStaffSchoolAssociationsValidateBeforeCall(Integer offset, Integer limit, Integer minChangeVersion, Integer maxChangeVersion, String snapshotIdentifier, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = deletesStaffSchoolAssociationsCall(offset, limit, minChangeVersion, maxChangeVersion, snapshotIdentifier, _callback);
        return localVarCall;

    }

    /**
     * Retrieves deleted resources based on change version.
     * The DELETES operation is used to retrieve deleted resources.
     * @param offset Indicates how many items should be skipped before returning results. (optional, default to 0)
     * @param limit Indicates the maximum number of items that should be returned in the results. (optional, default to 25)
     * @param minChangeVersion Used in synchronization to set sequence minimum ChangeVersion (optional)
     * @param maxChangeVersion Used in synchronization to set sequence maximum ChangeVersion (optional)
     * @param snapshotIdentifier Indicates the Snapshot-Identifier that should be used. (optional)
     * @return List&lt;DeletedResource&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The requested resource was successfully retrieved. </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> The resource&#39;s current server-side ETag value matched the If-None-Match header value supplied with the request indicating the resource has not been modified. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 410 </td><td> Gone. An attempt to connect to the database for the snapshot specified by the Snapshot-Identifier header was unsuccessful (indicating the snapshot may have been removed). </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public List<DeletedResource> deletesStaffSchoolAssociations(Integer offset, Integer limit, Integer minChangeVersion, Integer maxChangeVersion, String snapshotIdentifier) throws ApiException {
        ApiResponse<List<DeletedResource>> localVarResp = deletesStaffSchoolAssociationsWithHttpInfo(offset, limit, minChangeVersion, maxChangeVersion, snapshotIdentifier);
        return localVarResp.getData();
    }

    /**
     * Retrieves deleted resources based on change version.
     * The DELETES operation is used to retrieve deleted resources.
     * @param offset Indicates how many items should be skipped before returning results. (optional, default to 0)
     * @param limit Indicates the maximum number of items that should be returned in the results. (optional, default to 25)
     * @param minChangeVersion Used in synchronization to set sequence minimum ChangeVersion (optional)
     * @param maxChangeVersion Used in synchronization to set sequence maximum ChangeVersion (optional)
     * @param snapshotIdentifier Indicates the Snapshot-Identifier that should be used. (optional)
     * @return ApiResponse&lt;List&lt;DeletedResource&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The requested resource was successfully retrieved. </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> The resource&#39;s current server-side ETag value matched the If-None-Match header value supplied with the request indicating the resource has not been modified. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 410 </td><td> Gone. An attempt to connect to the database for the snapshot specified by the Snapshot-Identifier header was unsuccessful (indicating the snapshot may have been removed). </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<DeletedResource>> deletesStaffSchoolAssociationsWithHttpInfo(Integer offset, Integer limit, Integer minChangeVersion, Integer maxChangeVersion, String snapshotIdentifier) throws ApiException {
        okhttp3.Call localVarCall = deletesStaffSchoolAssociationsValidateBeforeCall(offset, limit, minChangeVersion, maxChangeVersion, snapshotIdentifier, null);
        Type localVarReturnType = new TypeToken<List<DeletedResource>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieves deleted resources based on change version. (asynchronously)
     * The DELETES operation is used to retrieve deleted resources.
     * @param offset Indicates how many items should be skipped before returning results. (optional, default to 0)
     * @param limit Indicates the maximum number of items that should be returned in the results. (optional, default to 25)
     * @param minChangeVersion Used in synchronization to set sequence minimum ChangeVersion (optional)
     * @param maxChangeVersion Used in synchronization to set sequence maximum ChangeVersion (optional)
     * @param snapshotIdentifier Indicates the Snapshot-Identifier that should be used. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The requested resource was successfully retrieved. </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> The resource&#39;s current server-side ETag value matched the If-None-Match header value supplied with the request indicating the resource has not been modified. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 410 </td><td> Gone. An attempt to connect to the database for the snapshot specified by the Snapshot-Identifier header was unsuccessful (indicating the snapshot may have been removed). </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deletesStaffSchoolAssociationsAsync(Integer offset, Integer limit, Integer minChangeVersion, Integer maxChangeVersion, String snapshotIdentifier, final ApiCallback<List<DeletedResource>> _callback) throws ApiException {

        okhttp3.Call localVarCall = deletesStaffSchoolAssociationsValidateBeforeCall(offset, limit, minChangeVersion, maxChangeVersion, snapshotIdentifier, _callback);
        Type localVarReturnType = new TypeToken<List<DeletedResource>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getStaffSchoolAssociations
     * @param offset Indicates how many items should be skipped before returning results. (optional, default to 0)
     * @param limit Indicates the maximum number of items that should be returned in the results. (optional, default to 25)
     * @param minChangeVersion Used in synchronization to set sequence minimum ChangeVersion (optional)
     * @param maxChangeVersion Used in synchronization to set sequence maximum ChangeVersion (optional)
     * @param totalCount Indicates if the total number of items available should be returned in the &#39;Total-Count&#39; header of the response.  If set to false, &#39;Total-Count&#39; header will not be provided. (optional, default to false)
     * @param programAssignmentDescriptor The name of the program for which the individual is assigned; for example:         Regular education         Title I-Academic         Title I-Non-Academic         Special Education         Bilingual/English as a Second Language. (optional)
     * @param schoolId The identifier assigned to a school. (optional)
     * @param staffUniqueId A unique alphanumeric code assigned to a staff. (optional)
     * @param calendarCode The identifier for the Calendar. (optional)
     * @param schoolYear Identifier for a school year. (optional)
     * @param id  (optional)
     * @param snapshotIdentifier Indicates the Snapshot-Identifier that should be used. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The requested resource was successfully retrieved. </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> The resource&#39;s current server-side ETag value matched the If-None-Match header value supplied with the request indicating the resource has not been modified. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 410 </td><td> Gone. An attempt to connect to the database for the snapshot specified by the Snapshot-Identifier header was unsuccessful (indicating the snapshot may have been removed). </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getStaffSchoolAssociationsCall(Integer offset, Integer limit, Integer minChangeVersion, Integer maxChangeVersion, Boolean totalCount, String programAssignmentDescriptor, Integer schoolId, String staffUniqueId, String calendarCode, Integer schoolYear, String id, String snapshotIdentifier, final ApiCallback _callback) throws ApiException {
        String basePath = null;

        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/ed-fi/staffSchoolAssociations";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (minChangeVersion != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("minChangeVersion", minChangeVersion));
        }

        if (maxChangeVersion != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("maxChangeVersion", maxChangeVersion));
        }

        if (totalCount != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("totalCount", totalCount));
        }

        if (programAssignmentDescriptor != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("programAssignmentDescriptor", programAssignmentDescriptor));
        }

        if (schoolId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("schoolId", schoolId));
        }

        if (staffUniqueId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("staffUniqueId", staffUniqueId));
        }

        if (calendarCode != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("calendarCode", calendarCode));
        }

        if (schoolYear != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("schoolYear", schoolYear));
        }

        if (id != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("id", id));
        }

        if (snapshotIdentifier != null) {
            localVarHeaderParams.put("Snapshot-Identifier", localVarApiClient.parameterToString(snapshotIdentifier));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2_client_credentials" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getStaffSchoolAssociationsValidateBeforeCall(Integer offset, Integer limit, Integer minChangeVersion, Integer maxChangeVersion, Boolean totalCount, String programAssignmentDescriptor, Integer schoolId, String staffUniqueId, String calendarCode, Integer schoolYear, String id, String snapshotIdentifier, final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = getStaffSchoolAssociationsCall(offset, limit, minChangeVersion, maxChangeVersion, totalCount, programAssignmentDescriptor, schoolId, staffUniqueId, calendarCode, schoolYear, id, snapshotIdentifier, _callback);
        return localVarCall;

    }

    /**
     * Retrieves specific resources using the resource&#39;s property values (using the \&quot;Get\&quot; pattern).
     * This GET operation provides access to resources using the \&quot;Get\&quot; search pattern.  The values of any properties of the resource that are specified will be used to return all matching results (if it exists).
     * @param offset Indicates how many items should be skipped before returning results. (optional, default to 0)
     * @param limit Indicates the maximum number of items that should be returned in the results. (optional, default to 25)
     * @param minChangeVersion Used in synchronization to set sequence minimum ChangeVersion (optional)
     * @param maxChangeVersion Used in synchronization to set sequence maximum ChangeVersion (optional)
     * @param totalCount Indicates if the total number of items available should be returned in the &#39;Total-Count&#39; header of the response.  If set to false, &#39;Total-Count&#39; header will not be provided. (optional, default to false)
     * @param programAssignmentDescriptor The name of the program for which the individual is assigned; for example:         Regular education         Title I-Academic         Title I-Non-Academic         Special Education         Bilingual/English as a Second Language. (optional)
     * @param schoolId The identifier assigned to a school. (optional)
     * @param staffUniqueId A unique alphanumeric code assigned to a staff. (optional)
     * @param calendarCode The identifier for the Calendar. (optional)
     * @param schoolYear Identifier for a school year. (optional)
     * @param id  (optional)
     * @param snapshotIdentifier Indicates the Snapshot-Identifier that should be used. (optional)
     * @return List&lt;EdFiStaffSchoolAssociation&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The requested resource was successfully retrieved. </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> The resource&#39;s current server-side ETag value matched the If-None-Match header value supplied with the request indicating the resource has not been modified. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 410 </td><td> Gone. An attempt to connect to the database for the snapshot specified by the Snapshot-Identifier header was unsuccessful (indicating the snapshot may have been removed). </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public List<EdFiStaffSchoolAssociation> getStaffSchoolAssociations(Integer offset, Integer limit, Integer minChangeVersion, Integer maxChangeVersion, Boolean totalCount, String programAssignmentDescriptor, Integer schoolId, String staffUniqueId, String calendarCode, Integer schoolYear, String id, String snapshotIdentifier) throws ApiException {
        ApiResponse<List<EdFiStaffSchoolAssociation>> localVarResp = getStaffSchoolAssociationsWithHttpInfo(offset, limit, minChangeVersion, maxChangeVersion, totalCount, programAssignmentDescriptor, schoolId, staffUniqueId, calendarCode, schoolYear, id, snapshotIdentifier);
        return localVarResp.getData();
    }

    /**
     * Retrieves specific resources using the resource&#39;s property values (using the \&quot;Get\&quot; pattern).
     * This GET operation provides access to resources using the \&quot;Get\&quot; search pattern.  The values of any properties of the resource that are specified will be used to return all matching results (if it exists).
     * @param offset Indicates how many items should be skipped before returning results. (optional, default to 0)
     * @param limit Indicates the maximum number of items that should be returned in the results. (optional, default to 25)
     * @param minChangeVersion Used in synchronization to set sequence minimum ChangeVersion (optional)
     * @param maxChangeVersion Used in synchronization to set sequence maximum ChangeVersion (optional)
     * @param totalCount Indicates if the total number of items available should be returned in the &#39;Total-Count&#39; header of the response.  If set to false, &#39;Total-Count&#39; header will not be provided. (optional, default to false)
     * @param programAssignmentDescriptor The name of the program for which the individual is assigned; for example:         Regular education         Title I-Academic         Title I-Non-Academic         Special Education         Bilingual/English as a Second Language. (optional)
     * @param schoolId The identifier assigned to a school. (optional)
     * @param staffUniqueId A unique alphanumeric code assigned to a staff. (optional)
     * @param calendarCode The identifier for the Calendar. (optional)
     * @param schoolYear Identifier for a school year. (optional)
     * @param id  (optional)
     * @param snapshotIdentifier Indicates the Snapshot-Identifier that should be used. (optional)
     * @return ApiResponse&lt;List&lt;EdFiStaffSchoolAssociation&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The requested resource was successfully retrieved. </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> The resource&#39;s current server-side ETag value matched the If-None-Match header value supplied with the request indicating the resource has not been modified. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 410 </td><td> Gone. An attempt to connect to the database for the snapshot specified by the Snapshot-Identifier header was unsuccessful (indicating the snapshot may have been removed). </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<EdFiStaffSchoolAssociation>> getStaffSchoolAssociationsWithHttpInfo(Integer offset, Integer limit, Integer minChangeVersion, Integer maxChangeVersion, Boolean totalCount, String programAssignmentDescriptor, Integer schoolId, String staffUniqueId, String calendarCode, Integer schoolYear, String id, String snapshotIdentifier) throws ApiException {
        okhttp3.Call localVarCall = getStaffSchoolAssociationsValidateBeforeCall(offset, limit, minChangeVersion, maxChangeVersion, totalCount, programAssignmentDescriptor, schoolId, staffUniqueId, calendarCode, schoolYear, id, snapshotIdentifier, null);
        Type localVarReturnType = new TypeToken<List<EdFiStaffSchoolAssociation>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieves specific resources using the resource&#39;s property values (using the \&quot;Get\&quot; pattern). (asynchronously)
     * This GET operation provides access to resources using the \&quot;Get\&quot; search pattern.  The values of any properties of the resource that are specified will be used to return all matching results (if it exists).
     * @param offset Indicates how many items should be skipped before returning results. (optional, default to 0)
     * @param limit Indicates the maximum number of items that should be returned in the results. (optional, default to 25)
     * @param minChangeVersion Used in synchronization to set sequence minimum ChangeVersion (optional)
     * @param maxChangeVersion Used in synchronization to set sequence maximum ChangeVersion (optional)
     * @param totalCount Indicates if the total number of items available should be returned in the &#39;Total-Count&#39; header of the response.  If set to false, &#39;Total-Count&#39; header will not be provided. (optional, default to false)
     * @param programAssignmentDescriptor The name of the program for which the individual is assigned; for example:         Regular education         Title I-Academic         Title I-Non-Academic         Special Education         Bilingual/English as a Second Language. (optional)
     * @param schoolId The identifier assigned to a school. (optional)
     * @param staffUniqueId A unique alphanumeric code assigned to a staff. (optional)
     * @param calendarCode The identifier for the Calendar. (optional)
     * @param schoolYear Identifier for a school year. (optional)
     * @param id  (optional)
     * @param snapshotIdentifier Indicates the Snapshot-Identifier that should be used. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The requested resource was successfully retrieved. </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> The resource&#39;s current server-side ETag value matched the If-None-Match header value supplied with the request indicating the resource has not been modified. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 410 </td><td> Gone. An attempt to connect to the database for the snapshot specified by the Snapshot-Identifier header was unsuccessful (indicating the snapshot may have been removed). </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getStaffSchoolAssociationsAsync(Integer offset, Integer limit, Integer minChangeVersion, Integer maxChangeVersion, Boolean totalCount, String programAssignmentDescriptor, Integer schoolId, String staffUniqueId, String calendarCode, Integer schoolYear, String id, String snapshotIdentifier, final ApiCallback<List<EdFiStaffSchoolAssociation>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getStaffSchoolAssociationsValidateBeforeCall(offset, limit, minChangeVersion, maxChangeVersion, totalCount, programAssignmentDescriptor, schoolId, staffUniqueId, calendarCode, schoolYear, id, snapshotIdentifier, _callback);
        Type localVarReturnType = new TypeToken<List<EdFiStaffSchoolAssociation>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getStaffSchoolAssociationsById
     * @param id A resource identifier that uniquely identifies the resource. (required)
     * @param ifNoneMatch The previously returned ETag header value, used here to prevent the unnecessary data transfer of an unchanged resource. (optional)
     * @param snapshotIdentifier Indicates the Snapshot-Identifier that should be used. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The requested resource was successfully retrieved. </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> The resource&#39;s current server-side ETag value matched the If-None-Match header value supplied with the request indicating the resource has not been modified. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 410 </td><td> Gone. An attempt to connect to the database for the snapshot specified by the Snapshot-Identifier header was unsuccessful (indicating the snapshot may have been removed). </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getStaffSchoolAssociationsByIdCall(String id, String ifNoneMatch, String snapshotIdentifier, final ApiCallback _callback) throws ApiException {
        String basePath = null;

        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/ed-fi/staffSchoolAssociations/{id}"
            .replaceAll("\\{" + "id" + "\\}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (ifNoneMatch != null) {
            localVarHeaderParams.put("If-None-Match", localVarApiClient.parameterToString(ifNoneMatch));
        }

        if (snapshotIdentifier != null) {
            localVarHeaderParams.put("Snapshot-Identifier", localVarApiClient.parameterToString(snapshotIdentifier));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2_client_credentials" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getStaffSchoolAssociationsByIdValidateBeforeCall(String id, String ifNoneMatch, String snapshotIdentifier, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getStaffSchoolAssociationsById(Async)");
        }
        

        okhttp3.Call localVarCall = getStaffSchoolAssociationsByIdCall(id, ifNoneMatch, snapshotIdentifier, _callback);
        return localVarCall;

    }

    /**
     * Retrieves a specific resource using the resource&#39;s identifier (using the \&quot;Get By Id\&quot; pattern).
     * This GET operation retrieves a resource by the specified resource identifier.
     * @param id A resource identifier that uniquely identifies the resource. (required)
     * @param ifNoneMatch The previously returned ETag header value, used here to prevent the unnecessary data transfer of an unchanged resource. (optional)
     * @param snapshotIdentifier Indicates the Snapshot-Identifier that should be used. (optional)
     * @return EdFiStaffSchoolAssociation
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The requested resource was successfully retrieved. </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> The resource&#39;s current server-side ETag value matched the If-None-Match header value supplied with the request indicating the resource has not been modified. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 410 </td><td> Gone. An attempt to connect to the database for the snapshot specified by the Snapshot-Identifier header was unsuccessful (indicating the snapshot may have been removed). </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public EdFiStaffSchoolAssociation getStaffSchoolAssociationsById(String id, String ifNoneMatch, String snapshotIdentifier) throws ApiException {
        ApiResponse<EdFiStaffSchoolAssociation> localVarResp = getStaffSchoolAssociationsByIdWithHttpInfo(id, ifNoneMatch, snapshotIdentifier);
        return localVarResp.getData();
    }

    /**
     * Retrieves a specific resource using the resource&#39;s identifier (using the \&quot;Get By Id\&quot; pattern).
     * This GET operation retrieves a resource by the specified resource identifier.
     * @param id A resource identifier that uniquely identifies the resource. (required)
     * @param ifNoneMatch The previously returned ETag header value, used here to prevent the unnecessary data transfer of an unchanged resource. (optional)
     * @param snapshotIdentifier Indicates the Snapshot-Identifier that should be used. (optional)
     * @return ApiResponse&lt;EdFiStaffSchoolAssociation&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The requested resource was successfully retrieved. </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> The resource&#39;s current server-side ETag value matched the If-None-Match header value supplied with the request indicating the resource has not been modified. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 410 </td><td> Gone. An attempt to connect to the database for the snapshot specified by the Snapshot-Identifier header was unsuccessful (indicating the snapshot may have been removed). </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<EdFiStaffSchoolAssociation> getStaffSchoolAssociationsByIdWithHttpInfo(String id, String ifNoneMatch, String snapshotIdentifier) throws ApiException {
        okhttp3.Call localVarCall = getStaffSchoolAssociationsByIdValidateBeforeCall(id, ifNoneMatch, snapshotIdentifier, null);
        Type localVarReturnType = new TypeToken<EdFiStaffSchoolAssociation>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieves a specific resource using the resource&#39;s identifier (using the \&quot;Get By Id\&quot; pattern). (asynchronously)
     * This GET operation retrieves a resource by the specified resource identifier.
     * @param id A resource identifier that uniquely identifies the resource. (required)
     * @param ifNoneMatch The previously returned ETag header value, used here to prevent the unnecessary data transfer of an unchanged resource. (optional)
     * @param snapshotIdentifier Indicates the Snapshot-Identifier that should be used. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The requested resource was successfully retrieved. </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> The resource&#39;s current server-side ETag value matched the If-None-Match header value supplied with the request indicating the resource has not been modified. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 410 </td><td> Gone. An attempt to connect to the database for the snapshot specified by the Snapshot-Identifier header was unsuccessful (indicating the snapshot may have been removed). </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getStaffSchoolAssociationsByIdAsync(String id, String ifNoneMatch, String snapshotIdentifier, final ApiCallback<EdFiStaffSchoolAssociation> _callback) throws ApiException {

        okhttp3.Call localVarCall = getStaffSchoolAssociationsByIdValidateBeforeCall(id, ifNoneMatch, snapshotIdentifier, _callback);
        Type localVarReturnType = new TypeToken<EdFiStaffSchoolAssociation>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postStaffSchoolAssociation
     * @param staffSchoolAssociation The JSON representation of the \&quot;staffSchoolAssociation\&quot; resource to be created or updated. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The resource was updated.  An updated ETag value is available in the ETag header of the response. </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> The resource was created.  An ETag value is available in the ETag header, and the location of the resource is available in the Location header of the response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Is Not Allowed. When the Snapshot-Identifier header is present the method is not allowed. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict.  The request cannot be completed because it would result in an invalid state.  See the response body for details. </td><td>  -  </td></tr>
        <tr><td> 412 </td><td> The resource&#39;s current server-side ETag value does not match the supplied If-Match header value in the request. This indicates the resource has been modified by another consumer. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postStaffSchoolAssociationCall(EdFiStaffSchoolAssociation staffSchoolAssociation, final ApiCallback _callback) throws ApiException {
        String basePath = null;

        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = staffSchoolAssociation;

        // create path and map variables
        String localVarPath = "/ed-fi/staffSchoolAssociations";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2_client_credentials" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postStaffSchoolAssociationValidateBeforeCall(EdFiStaffSchoolAssociation staffSchoolAssociation, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'staffSchoolAssociation' is set
        if (staffSchoolAssociation == null) {
            throw new ApiException("Missing the required parameter 'staffSchoolAssociation' when calling postStaffSchoolAssociation(Async)");
        }
        

        okhttp3.Call localVarCall = postStaffSchoolAssociationCall(staffSchoolAssociation, _callback);
        return localVarCall;

    }

    /**
     * Creates or updates resources based on the natural key values of the supplied resource.
     * The POST operation can be used to create or update resources. In database terms, this is often referred to as an \&quot;upsert\&quot; operation (insert + update). Clients should NOT include the resource \&quot;id\&quot; in the JSON body because it will result in an error. The web service will identify whether the resource already exists based on the natural key values provided, and update or create the resource appropriately. It is recommended to use POST for both create and update except while updating natural key of a resource in which case PUT operation must be used.
     * @param staffSchoolAssociation The JSON representation of the \&quot;staffSchoolAssociation\&quot; resource to be created or updated. (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The resource was updated.  An updated ETag value is available in the ETag header of the response. </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> The resource was created.  An ETag value is available in the ETag header, and the location of the resource is available in the Location header of the response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Is Not Allowed. When the Snapshot-Identifier header is present the method is not allowed. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict.  The request cannot be completed because it would result in an invalid state.  See the response body for details. </td><td>  -  </td></tr>
        <tr><td> 412 </td><td> The resource&#39;s current server-side ETag value does not match the supplied If-Match header value in the request. This indicates the resource has been modified by another consumer. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public void postStaffSchoolAssociation(EdFiStaffSchoolAssociation staffSchoolAssociation) throws ApiException {
        postStaffSchoolAssociationWithHttpInfo(staffSchoolAssociation);
    }

    /**
     * Creates or updates resources based on the natural key values of the supplied resource.
     * The POST operation can be used to create or update resources. In database terms, this is often referred to as an \&quot;upsert\&quot; operation (insert + update). Clients should NOT include the resource \&quot;id\&quot; in the JSON body because it will result in an error. The web service will identify whether the resource already exists based on the natural key values provided, and update or create the resource appropriately. It is recommended to use POST for both create and update except while updating natural key of a resource in which case PUT operation must be used.
     * @param staffSchoolAssociation The JSON representation of the \&quot;staffSchoolAssociation\&quot; resource to be created or updated. (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The resource was updated.  An updated ETag value is available in the ETag header of the response. </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> The resource was created.  An ETag value is available in the ETag header, and the location of the resource is available in the Location header of the response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Is Not Allowed. When the Snapshot-Identifier header is present the method is not allowed. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict.  The request cannot be completed because it would result in an invalid state.  See the response body for details. </td><td>  -  </td></tr>
        <tr><td> 412 </td><td> The resource&#39;s current server-side ETag value does not match the supplied If-Match header value in the request. This indicates the resource has been modified by another consumer. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> postStaffSchoolAssociationWithHttpInfo(EdFiStaffSchoolAssociation staffSchoolAssociation) throws ApiException {
        okhttp3.Call localVarCall = postStaffSchoolAssociationValidateBeforeCall(staffSchoolAssociation, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Creates or updates resources based on the natural key values of the supplied resource. (asynchronously)
     * The POST operation can be used to create or update resources. In database terms, this is often referred to as an \&quot;upsert\&quot; operation (insert + update). Clients should NOT include the resource \&quot;id\&quot; in the JSON body because it will result in an error. The web service will identify whether the resource already exists based on the natural key values provided, and update or create the resource appropriately. It is recommended to use POST for both create and update except while updating natural key of a resource in which case PUT operation must be used.
     * @param staffSchoolAssociation The JSON representation of the \&quot;staffSchoolAssociation\&quot; resource to be created or updated. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The resource was updated.  An updated ETag value is available in the ETag header of the response. </td><td>  -  </td></tr>
        <tr><td> 201 </td><td> The resource was created.  An ETag value is available in the ETag header, and the location of the resource is available in the Location header of the response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Is Not Allowed. When the Snapshot-Identifier header is present the method is not allowed. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict.  The request cannot be completed because it would result in an invalid state.  See the response body for details. </td><td>  -  </td></tr>
        <tr><td> 412 </td><td> The resource&#39;s current server-side ETag value does not match the supplied If-Match header value in the request. This indicates the resource has been modified by another consumer. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postStaffSchoolAssociationAsync(EdFiStaffSchoolAssociation staffSchoolAssociation, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = postStaffSchoolAssociationValidateBeforeCall(staffSchoolAssociation, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for putStaffSchoolAssociation
     * @param id A resource identifier that uniquely identifies the resource. (required)
     * @param staffSchoolAssociation The JSON representation of the \&quot;staffSchoolAssociation\&quot; resource to be created or updated. (required)
     * @param ifMatch The ETag header value used to prevent the PUT from updating a resource modified by another consumer. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> The resource was updated.  An updated ETag value is available in the ETag header of the response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Is Not Allowed. When the Snapshot-Identifier header is present the method is not allowed. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict.  The request cannot be completed because it would result in an invalid state.  See the response body for details. </td><td>  -  </td></tr>
        <tr><td> 412 </td><td> The resource&#39;s current server-side ETag value does not match the supplied If-Match header value in the request. This indicates the resource has been modified by another consumer. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call putStaffSchoolAssociationCall(String id, EdFiStaffSchoolAssociation staffSchoolAssociation, String ifMatch, final ApiCallback _callback) throws ApiException {
        String basePath = null;

        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = staffSchoolAssociation;

        // create path and map variables
        String localVarPath = "/ed-fi/staffSchoolAssociations/{id}"
            .replaceAll("\\{" + "id" + "\\}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (ifMatch != null) {
            localVarHeaderParams.put("If-Match", localVarApiClient.parameterToString(ifMatch));
        }

        final String[] localVarAccepts = {
            
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2_client_credentials" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call putStaffSchoolAssociationValidateBeforeCall(String id, EdFiStaffSchoolAssociation staffSchoolAssociation, String ifMatch, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling putStaffSchoolAssociation(Async)");
        }
        
        // verify the required parameter 'staffSchoolAssociation' is set
        if (staffSchoolAssociation == null) {
            throw new ApiException("Missing the required parameter 'staffSchoolAssociation' when calling putStaffSchoolAssociation(Async)");
        }
        

        okhttp3.Call localVarCall = putStaffSchoolAssociationCall(id, staffSchoolAssociation, ifMatch, _callback);
        return localVarCall;

    }

    /**
     * Updates a resource based on the resource identifier.
     * The PUT operation is used to update a resource by identifier. If the resource identifier (\&quot;id\&quot;) is provided in the JSON body, it will be ignored. Additionally, this API resource is not configured for cascading natural key updates. Natural key values for this resource cannot be changed using PUT operation and will not be modified in the database, and so recommendation is to use POST as that supports upsert behavior.
     * @param id A resource identifier that uniquely identifies the resource. (required)
     * @param staffSchoolAssociation The JSON representation of the \&quot;staffSchoolAssociation\&quot; resource to be created or updated. (required)
     * @param ifMatch The ETag header value used to prevent the PUT from updating a resource modified by another consumer. (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> The resource was updated.  An updated ETag value is available in the ETag header of the response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Is Not Allowed. When the Snapshot-Identifier header is present the method is not allowed. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict.  The request cannot be completed because it would result in an invalid state.  See the response body for details. </td><td>  -  </td></tr>
        <tr><td> 412 </td><td> The resource&#39;s current server-side ETag value does not match the supplied If-Match header value in the request. This indicates the resource has been modified by another consumer. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public void putStaffSchoolAssociation(String id, EdFiStaffSchoolAssociation staffSchoolAssociation, String ifMatch) throws ApiException {
        putStaffSchoolAssociationWithHttpInfo(id, staffSchoolAssociation, ifMatch);
    }

    /**
     * Updates a resource based on the resource identifier.
     * The PUT operation is used to update a resource by identifier. If the resource identifier (\&quot;id\&quot;) is provided in the JSON body, it will be ignored. Additionally, this API resource is not configured for cascading natural key updates. Natural key values for this resource cannot be changed using PUT operation and will not be modified in the database, and so recommendation is to use POST as that supports upsert behavior.
     * @param id A resource identifier that uniquely identifies the resource. (required)
     * @param staffSchoolAssociation The JSON representation of the \&quot;staffSchoolAssociation\&quot; resource to be created or updated. (required)
     * @param ifMatch The ETag header value used to prevent the PUT from updating a resource modified by another consumer. (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> The resource was updated.  An updated ETag value is available in the ETag header of the response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Is Not Allowed. When the Snapshot-Identifier header is present the method is not allowed. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict.  The request cannot be completed because it would result in an invalid state.  See the response body for details. </td><td>  -  </td></tr>
        <tr><td> 412 </td><td> The resource&#39;s current server-side ETag value does not match the supplied If-Match header value in the request. This indicates the resource has been modified by another consumer. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> putStaffSchoolAssociationWithHttpInfo(String id, EdFiStaffSchoolAssociation staffSchoolAssociation, String ifMatch) throws ApiException {
        okhttp3.Call localVarCall = putStaffSchoolAssociationValidateBeforeCall(id, staffSchoolAssociation, ifMatch, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Updates a resource based on the resource identifier. (asynchronously)
     * The PUT operation is used to update a resource by identifier. If the resource identifier (\&quot;id\&quot;) is provided in the JSON body, it will be ignored. Additionally, this API resource is not configured for cascading natural key updates. Natural key values for this resource cannot be changed using PUT operation and will not be modified in the database, and so recommendation is to use POST as that supports upsert behavior.
     * @param id A resource identifier that uniquely identifies the resource. (required)
     * @param staffSchoolAssociation The JSON representation of the \&quot;staffSchoolAssociation\&quot; resource to be created or updated. (required)
     * @param ifMatch The ETag header value used to prevent the PUT from updating a resource modified by another consumer. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> The resource was updated.  An updated ETag value is available in the ETag header of the response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request. The request was invalid and cannot be completed. See the response body for specific validation errors. This will typically be an issue with the query parameters or their values. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized. The request requires authentication. The OAuth bearer token was either not provided or is invalid. The operation may succeed once authentication has been successfully completed. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Forbidden. The request cannot be completed in the current authorization context. Contact your administrator if you believe this operation should be allowed. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The resource could not be found. </td><td>  -  </td></tr>
        <tr><td> 405 </td><td> Method Is Not Allowed. When the Snapshot-Identifier header is present the method is not allowed. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Conflict.  The request cannot be completed because it would result in an invalid state.  See the response body for details. </td><td>  -  </td></tr>
        <tr><td> 412 </td><td> The resource&#39;s current server-side ETag value does not match the supplied If-Match header value in the request. This indicates the resource has been modified by another consumer. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unhandled error occurred on the server. See the response body for details. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call putStaffSchoolAssociationAsync(String id, EdFiStaffSchoolAssociation staffSchoolAssociation, String ifMatch, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = putStaffSchoolAssociationValidateBeforeCall(id, staffSchoolAssociation, ifMatch, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
